/*
 * Copyright 2025 coze-dev Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
 
// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

export type Int64 = string | number;

export enum AsyncTaskStatusForPlugin {
  /** unknown state */
  Unknown = 0,
  /** Created successfully */
  CreateSucceed = 1,
  /** run */
  Executing = 2,
  /** Pushing */
  Pushing = 3,
  /** successful execution */
  ExecuteSucceed = 10,
  /** execution failed */
  ExecuteFailed = 11,
}

export enum AsyncTaskStatusForUser {
  /** unknown state */
  Unknown = 0,
  /** in progress */
  Executing = 1,
  /** successful execution */
  ExecuteSucceed = 2,
  /** execution failed */
  ExecuteFailed = 3,
}

export enum AsyncType {
  /** Unknown type */
  Unknown = 0,
  /** plugin asynchronous task */
  Workflow = 1,
  /** native asynchronous plugin */
  NativeAsyncPlugin = 2,
  /** synchronous to asynchronous plugin */
  SyncToAsyncPlugin = 3,
}

export enum AttributeValueType {
  Unknown = 0,
  String = 1,
  Boolean = 2,
  StringList = 11,
  BooleanList = 12,
}

export enum CozeReleaseChannel {
  Inhouse = 0,
  Release = 1,
}

export enum DebugExampleStatus {
  Default = 0,
  Enable = 1,
  Disable = 2,
}

export enum FeedbackType {
  Unknown = 0,
  /** The required plugin was not found */
  NotFoundPlugin = 1,
  /** Official plugin feedback */
  OfficialPlugin = 2,
}

export enum GrantType {
  TokenExchange = 1,
  ClientCredential = 2,
}

/** operation type */
export enum OperateType {
  Add = 0,
  Delete = 1,
}

/** Add channel id */
export enum PluginChannel {
  /** All channels */
  All = 0,
  /** material */
  Material = 1,
  /** store */
  Store = 2,
}

/** Fusion plugin product upload and removal and review status, for front-end use */
export enum PluginProductStatus {
  Default = 0,
  Listed = 1,
  Unlisted = 2,
  Reviewing = 3,
}

/** Plugin update type */
export enum PluginUpdateEventType {
  /** transfer space */
  TransferSpace = 1,
  /** Transfer owner */
  TransferOwner = 2,
}

export enum PrivacyAuthStatus {
  Unauthorized = 1,
  Authorized = 2,
}

/** Plugin authorization type */
export enum PrivacyAuthType {
  /** ask */
  Ask = 0,
  /** Only this time allowed */
  Once = 1,
  /** Always allow */
  Always = 2,
}

/** ==================== Project IDE Begin ====================
 AuthZ interface */
export enum ResourceType {
  Account = 1,
  Workspace = 2,
  App = 3,
  Bot = 4,
  Plugin = 5,
  Workflow = 6,
  Knowledge = 7,
  PersonalAccessToken = 8,
  Connector = 9,
  Card = 10,
  CardTemplate = 11,
  Conversation = 12,
  File = 13,
  ServicePrincipal = 14,
  Enterprise = 15,
  MigrateTask = 16,
  Prompt = 17,
  UI = 18,
  Project = 19,
}

export enum ServiceAuthSubType {
  ApiKey = 0,
  BytedanceZeroTrust = 1,
  OIDC = 2,
}

export enum TcsAuditStatus {
  /** default state */
  Default = 0,
  /** approved */
  AuditPass = 1,
  /** The review failed. */
  AuditReject = 2,
}

export interface AsyncPluginTaskFinishMessage {
  /** Task ID */
  serial_id?: string;
  /** Plugin ID */
  plugin_id?: Int64;
  /** Plugin apiName */
  api_name?: string;
  /** extended field */
  ext?: Record<string, string>;
  /** Was the task successful? */
  is_succeed?: boolean;
  /** message delivery time */
  event_time?: string;
}

export interface AttributeValue {
  Type: AttributeValueType;
  Value: string;
}

export interface CardBindInfo {
  CardID?: Int64;
  MappingRule?: string;
  MaxDisplayRows?: Int64;
  CardVersion?: Int64;
  LlmTextCard?: boolean;
  /** Whether the exported parameter matches MappingRule, some interfaces will set this value */
  OutputParamMatch?: boolean;
}

export interface ExecuteDisplayName {
  /** Execution display name, nil means not set */
  name_executing?: string;
  /** Executed display name, nil means not set */
  name_executed?: string;
  /** The display name of the execution failure, nil means not set */
  name_execute_failed?: string;
}

export interface OIDCPayload {
  grant_type?: GrantType;
  endpoint_url?: string;
  audience?: string;
  oidc_scope?: string;
  oidc_client_id?: string;
}

export interface PluginPrivacyAuth {
  /** Plugin ID */
  plugin_id?: Int64;
  /** plugin name */
  plugin_name?: string;
  /** authorization type */
  auth_type?: PrivacyAuthType;
}

export interface PluginPublishInfo {
  /** publisher */
  PublisherID?: Int64;
  /** Version, millisecond timestamp */
  VersionTs?: Int64;
  /** version name */
  VersionName?: string;
  /** version description */
  VersionDesc?: string;
}

export interface PluginUnauthorizedInfo {
  /** Plugin ID */
  plugin_id?: Int64;
  /** plugin name */
  plugin_name?: string;
}

export interface PluginUpdateEvent {
  /** channel plugin id */
  channel_plugin_id?: Int64;
  /** Material ID */
  material_id?: Int64;
  /** event type */
  event_type?: PluginUpdateEventType;
  /** message delivery time */
  event_time?: Int64;
  /** source user id */
  source_user_id?: Int64;
  /** Target user id */
  target_user_id?: Int64;
  /** Target space id */
  target_space_id?: Int64;
}

export interface PrivacyAuthStatusInfo {
  PluginId?: Int64;
  /** authorization status */
  Status?: PrivacyAuthStatus;
}

export interface ResourceCopyResultInfo {
  /** If the plugin is copied, record the tool ID mapping */
  ApiIdMapping?: Record<Int64, Int64>;
}

export interface ResourceIdentifier {
  /** resource type */
  Type: ResourceType;
  /** Resource Id */
  Id: string;
}
/* eslint-enable */
