/*
 * Copyright 2025 coze-dev Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
 
// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

export type Int64 = string | number;

export enum SliceStatus {
  /** unvectorized */
  PendingVectoring = 0,
  /** vectorized */
  FinishVectoring = 1,
  /** disable */
  Deactive = 9,
}

export interface ChangeSliceStatusReq {
  slice_id: string;
  status: SliceStatus;
}

export interface CreateSliceData {
  slice_id?: string;
}

export interface CreateSliceReq {
  document_id: string;
  /** Limit 2000 words */
  content: string;
}

export interface CreateSliceResp {
  code?: number;
  msg?: string;
  data?: CreateSliceData;
}

export interface DelSliceReq {
  slice_id: string;
}

export interface GetSliceListData {
  data?: Array<SliceInfo>;
  total?: number;
}

export interface GetSliceListReq {
  doc_id?: string;
  /** serial number */
  sequence?: number;
  /** query keyword */
  key_word?: string;
  /** Start from 1 */
  page_no?: number;
  /** quantity */
  page_size?: number;
  sort_field?: string;
  is_asc?: boolean;
}

export interface GetSliceListResp {
  code?: number;
  msg?: string;
  data?: GetSliceListData;
}

export interface SliceInfo {
  slice_id?: string;
  /** If it is a table type, the content is in JSON format */
  content?: string;
  /** state */
  status?: SliceStatus;
  /** hit count */
  hit_count?: number;
  /** character count */
  char_count?: number;
  /** number of tokens */
  token_count?: number;
  /** serial number */
  sequence?: number;
}

export interface UpdateSliceContentReq {
  slice_id: string;
  /** Limit 2000 words */
  content: string;
}
/* eslint-enable */
