/*
 * Copyright 2025 coze-dev Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
 
// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

export type Int64 = string;

export enum AuditStatus {
  /** default */
  Default = 0,
  /** Under review. */
  Pending = 1,
  /** approved */
  Approved = 2,
  /** The review failed. */
  Rejected = 3,
  /** Abandoned */
  Abandoned = 4,
  /** abnormal */
  Failed = 99,
}

export enum AuditType {
  ProductDraft = 10,
  /** user */
  UserProfile = 18,
  /** Share the conversation */
  ConversationShared = 19,
  /** referral dialogue */
  Conversation = 20,
  InterationPost = 21,
  InterationComment = 22,
  ProductWorkFlow = 23,
  ProductBot = 24,
  ProductPlugin = 25,
  ImageFlowUploadImages = 26,
  ImageFlowTestRun = 27,
  ImageFlowPluginOutput = 28,
  DataEngineKnowledge = 29,
  BotAvatar = 30,
  BotPublishSingleBot = 31,
  BotPublishMultiAgent = 32,
  BotPublishPlugin = 33,
  BotPublishWorkflow = 34,
  BotModify = 35,
  BotCreate = 36,
  BotWorkflowAsAgentPublish = 37,
  BotWorkflowAsAgentModify = 38,
  BotSingleAgentModify = 39,
  SocietyCreate = 40,
  SocietyPublish = 41,
  SocietyRoleCreate = 42,
  SocietyPrePublish = 43,
  ProductSociety = 44,
  ProductImageFlow = 46,
  PluginImageGenerateInput = 48,
  PluginImageGenerateOutputImage = 49,
  PluginImageGenerateOutputVideo = 50,
  PluginCreate = 51,
  PluginModify = 52,
  VariableModify = 53,
  CardInfo = 60,
  AgentAppWriter = 80,
  /** Model Square Battle Query */
  ModelArenaQuery = 81,
  /** message link tracing */
  MessageTrace = 82,
  /** Library Prompt */
  ResourcePrompt = 83,
  /** ProjectIDE modification */
  ProjectIDEModify = 84,
  /** Bot template */
  TemplateBot = 85,
  /** workflow template */
  TemplateWorkflow = 86,
  /** Project Template */
  TemplateProject = 87,
  /** Project goods */
  ProductProject = 88,
  /** Project launch */
  ProjectPublish = 89,
  /** Project UI Builder */
  ProjectUIBuilder = 90,
  /** Workflow runtime input */
  WorkflowRuntimeInput = 100,
  /** voice runtime input */
  AudioRuntimeInput = 101,
  /** voice resource */
  AudioVoiceResource = 102,
  /** Model fine-tuning input */
  ModelFinetuneInput = 103,
  /** OpenAPI image upload */
  OpenAPIImageUpload = 104,
  /** App (Project) Audio */
  AppAudio = 105,
  /** Business creation/modification */
  EnterpriseModify = 106,
  CozeLoopPEModify = 107,
  CozeLoopExptModify = 108,
  CozeLoopDatasetModify = 109,
  CozeLoopEvaluatorModify = 110,
  /** CozeSpace */
  CozeSpaceQuery = 111,
  /** CozeSpace answers */
  CozeSpaceAnswer = 112,
  /** CozeSpace TraeBuilder Query */
  CozeSpaceTraeBuilderQuery = 113,
  /** CozeSpace TraeBuilder Answers */
  CozeSpaceTraeBuilderAnswer = 114,
  /** CozeSpace web searchQuery */
  CozeSpaceSearchWebQuery = 115,
  /** Answers to CozeSpace web search */
  CozeSpaceSearchWebAnswer = 116,
  /** CozeSpace Img Search Query */
  CozeSpaceSearchImgQuery = 117,
  /** CozeSpace Img Search Answers */
  CozeSpaceSearchImgAnswer = 118,
  /** CozeSpace Timed TaskQuery */
  CozeSpaceScheduleTaskQuery = 119,
  /** Voiceprint creation/modification */
  VoicePrintGroup = 120,
  /** Voiceprint feature creation/modification */
  VoicePrintGroupFeature = 121,
  /** video generation input */
  VideoGenerateInput = 122,
  /** CozeSpace PPT Agent Modification */
  CozeSpacePPTAgentModify = 123,
}

export enum QueueType {
  /** default queue */
  Default = 0,
  /** recall queue */
  Recall = 1,
  /** report queue */
  Report = 2,
  /** offline recall */
  Review = 3,
}

export enum RefuseReason {
  /** other */
  Other = 0,
  /** drainage advertisement */
  Ad = 1,
  /** uncomfortable */
  Uncomfortable = 2,
  /** violation of laws and regulations */
  Illegal = 3,
  /** religious cult */
  Cult = 4,
  /** Public order and good customs */
  Morals = 5,
  /** erotic vulgarity */
  Porn = 6,
  /** involved leaders */
  Leaders = 7,
  /** Party and government sensitivity */
  SensitiveParty = 8,
  /** The Privacy Policy contains invalid content (e.g. the link is invalid, cannot be opened, and the contact information is invalid) */
  InvalidContent = 9,
  /** illegal link */
  LinksIllegal = 10,
}

export enum ReviewRefuseModule {
  /** Bot 1XXX */
  BotPublish = 1000,
  BotPublishBotIcon = 1001,
  BotPublishBotName = 1002,
  BotPublishBotDesc = 1003,
  BotPublishBotPrompt = 1004,
  BotPublishBotDatabase = 1005,
  BotPublishBotTask = 1006,
  BotPublishBotOnboardingPrologue = 1007,
  BotPublishBotOnboardingSuggestedQuestions = 1008,
  BotPublishBotSuggestReply = 1009,
  BotPublishBotBackgroundImage = 1010,
  BotPublishBotShortcutCommandList = 1011,
  BotPublishBotQueryCollectConf = 1012,
  BotPublishSimpleAgentName = 1013,
  BotPublishSimpleAgentPrompt = 1014,
  BotPublishSimpleAgentScene = 1015,
  BotPublishSimpleAgentSkills = 1016,
  BotPublishSimpleAgentSuggestReplyInfo = 1017,
  BotPublishBotAgentBotIcon = 1018,
  BotPublishBotAgentBotName = 1019,
  BotPublishBotAgentScene = 1020,
  BotPublishBotAgentSuggestReplyInfo = 1021,
  BotPublishGlobalJumpConditions = 1022,
  BotPublishPlugin = 1200,
  BotPublishWorkflow = 1300,
  /** ProductPlugin 22XX */
  ProductPlugin = 2200,
  ProductPluginProductInfo = 2201,
  ProductPluginPluginInfo = 2202,
  ProductPluginAPIs = 2203,
  /** ProductWorkflow 23XX */
  ProductWorkflow = 2300,
  /** ProductImageFlow 24XX */
  ProductImageFlow = 2400,
  /** InteractionPost 31XX */
  InteractionPost = 3100,
  /** InteractionComment 32XX */
  InteractionComment = 3200,
  /** Society 4XXX */
  Society = 4000,
  SocietyBasicInfoIcon = 4001,
  SocietyBasicInfoName = 4002,
  SocietyBasicInfoDesc = 4003,
  SocietyBasicInfoPrompt = 4004,
  SocietyHostInfoIcon = 4005,
  SocietyHostInfoName = 4006,
  SocietyHostInfoDesc = 4007,
  SocietyRoleInfoIcon = 4008,
  SocietyRoleInfoName = 4009,
  SocietyRoleInfoDesc = 4010,
  SocietyRoleInfoNickName = 4011,
  /** Project 5XXX */
  Project = 5000,
  ProjectBasicInfoName = 5001,
  ProjectBasicInfoDesc = 5002,
  ProjectBasicInfoIcon = 5003,
  ProjectPlugin = 5100,
  ProjectWorkflow = 5200,
  ProjectUI = 5300,
  ProjectData = 5400,
}

export interface AuditExtra {
  AuditContext?: string;
  OperationMap?: Record<string, Array<string>>;
  QueueType?: QueueType;
}

export interface AuditRecord {
  ObjectID: Int64;
  AuditType: AuditType;
  AuditStatus: AuditStatus;
  Extra?: AuditExtra;
  FailedReason?: string;
  ReqID?: string;
}
/* eslint-enable */
