/*
 * Copyright 2025 coze-dev Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
 
// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

export type Int64 = string | number;

export enum DouYinDeployStatus {
  /** Deploying */
  Deploying = 0,
  /** Successful deployment */
  Successful = 1,
  /** deployment failed */
  Failed = 2,
}

export enum DouYinFenShenBindStatus {
  /** All status */
  All = 0,
  /** Binding state */
  Bind = 1,
  /** unbound state */
  UnBind = 2,
}

export enum DouYinFenShenOrderBy {
  CreateTime = 0,
  UpdateTime = 1,
}

export interface DebugDouYinData {
  deploy_status: DouYinDeployStatus;
  deploy_qr_code?: string;
}

export interface DebugDouYinRequest {
  bot_id: string;
}

export interface DebugDouYinResponse {
  data?: DebugDouYinData;
  code: Int64;
  msg: string;
}

export interface DouYinAuthUserInfo {
  /** Douyin nickname */
  nickname: string;
  /** Douyin avatar */
  icon: string;
  /** doppelganger app */
  app_id: string;
  /** authorization time */
  create_time: string;
  /** Binding Status 1 Bound 2 Unbound */
  bind_status: DouYinFenShenBindStatus;
}

export interface DouYinAuthUserListData {
  list?: Array<DouYinAuthUserInfo>;
  total?: Int64;
}

export interface DouYinAuthUserListRequest {
  /** Start from 1 */
  page_index: number;
  /** Up to 50 */
  page_size: number;
  /** Binding status, default all */
  bind_status?: DouYinFenShenBindStatus;
  /** Sort by creation time by default */
  order_by?: DouYinFenShenOrderBy;
}

export interface DouYinAuthUserListResponse {
  data?: DouYinAuthUserListData;
  code: Int64;
  msg: string;
}

export interface DouYinCallbackRequest {
  EventName: string;
  EventMsgBody: string;
}

export interface DouYinCallbackResponse {
  code: Int64;
  msg: string;
}

export interface GetDouYinAppAuthTokenRequest {
  /** The object ID associated with the Douyin doppelganger */
  AssociateEntityId: Int64;
  /** Douyin doppelganger ID */
  AppId?: string;
}

export interface GetDouYinAppAuthTokenResponse {
  Token?: string;
  AppId?: string;
  code: Int64;
  msg: string;
}

export interface GetDouYinAuthCodeData {
  /** The QR code corresponding to the authorization code link, use base64 to convert it into a picture and scan the code. */
  qr_code_pic_base64: string;
  /** Authorization QR code expiration time, second timestamp */
  expires_in: string;
}

export interface GetDouYinAuthCodeRequest {}

export interface GetDouYinAuthCodeResponse {
  data?: GetDouYinAuthCodeData;
  code: Int64;
  msg: string;
}

export interface GetDouyinAvatarInfoData {
  /** bot_common json string for botInfo */
  bot_info?: string;
  /** Model mapping key = model_id value = Douyin ep_name */
  model_info?: Record<string, string>;
  /** Model capability key = model_id value = model_manage model_desc structure serialization returned */
  model_desc?: Record<string, string>;
}

export interface GetDouyinAvatarInfoRequest {
  /** The doppelganger application app_id extracted from the request header = Open-Platform-App-ID */
  'Open-Platform-App-ID'?: string;
  /** Is it a draft? */
  is_draft?: boolean;
  body?: Blob;
  'Byte-Signature'?: string;
  'Byte-Timestamp'?: string;
  'Byte-Nonce-Str'?: string;
}

export interface GetDouyinAvatarInfoResponse {
  data: GetDouyinAvatarInfoData;
  code: Int64;
  msg: string;
}

export interface GetDouYinInfoData {
  industry_list?: Array<string>;
}

export interface GetDouYinInfoRequest {}

export interface GetDouYinInfoResponse {
  data?: GetDouYinInfoData;
  code: Int64;
  msg: string;
}
/* eslint-enable */
