/*
 * Copyright 2025 coze-dev Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
 
// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

import * as uniexam from './uniexam';
import * as base from './base';

export type Int64 = string | number;

/** Title correction status */
export enum ExternalUserStatus {
  /** disable */
  Disabled = 0,
  /** enable */
  Enabled = 1,
}

export interface ConfirmUniExamRecordForExternalReq {
  /** External Exam Record ID */
  external_id?: string;
  /** Listening test paper grade */
  listening_paper_level?: uniexam.GeneralLevel;
  /** Listening score */
  listening_score?: number;
  /** Hearing level */
  listening_level?: uniexam.DetailLevel;
  /** spoken score */
  oral_score?: number;
  /** speaking level */
  oral_level?: uniexam.DetailLevel;
  /** Final grading (if the final grading is not passed, only the score is saved, and the status remains unchanged. If the final grading is passed, it will be confirmed that it will be submitted for correction, and the status will be changed to completed) */
  final_level?: uniexam.DetailLevel;
  /** Confirmation Type (0: Unknown 1: Confirmation 2: Save) */
  confirm_type?: uniexam.ConfirmUniExamType;
  base?: base.Base;
}

export interface ConfirmUniExamRecordForExternalResp {
  uni_exam?: uniexam.UniExam;
  code?: number;
  message?: string;
  base_resp?: base.BaseResp;
}

export interface GetUniExamRecordForExternalReq {
  /** External Exam Record ID */
  id?: string;
  base?: base.Base;
}

export interface GetUniExamRecordForExternalResp {
  uni_exam?: uniexam.UniExam;
  code?: number;
  message?: string;
  base_resp?: base.BaseResp;
}

export interface ListUniExamRecordForExternalReq {
  /** page number */
  page?: number;
  /** number of pages per page */
  page_size?: number;
  /** External Exam ID */
  exam_id?: string;
  base?: base.Base;
}

export interface ListUniExamRecordForExternalResp {
  uni_exams?: Array<uniexam.UniExam>;
  total?: number;
  page?: number;
  page_size?: number;
  code?: number;
  message?: string;
  base_resp?: base.BaseResp;
}

export interface LoginByBasicReq {
  /** user name */
  email?: string;
  /** password */
  password?: string;
  base?: base.Base;
}

export interface LoginByBasicResp {
  base_resp?: base.BaseResp;
}

export interface LogoutByBasicReq {
  base?: base.Base;
}

export interface LogoutByBasicResp {
  base_resp?: base.BaseResp;
}
/* eslint-enable */
