/*
 * Copyright 2025 coze-dev Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
 
// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

import * as base from './base';

export type Int64 = string | number;

export enum ComponentCreateStatus {
  Undefined = 0,
  /** Creating */
  Creating = 1,
  /** Created successfully */
  CreateSuccess = 2,
  /** Failed to create */
  CreateFailed = 3,
}

export enum ComponentLanguage {
  Undefined = 0,
  Go = 1,
}

export enum ComponentReleaseStatus {
  Undefined = 0,
  /** In release */
  InRelease = 1,
  /** Published successfully */
  ReleaseSuccess = 2,
  /** publish failed */
  ReleaseFailed = 3,
}

/** component type enumeration */
export enum ComponentType {
  Undefined = 0,
  ChatModel = 1,
  ToolAgent = 2,
}

export interface ComponentTemplateInfo {
  /** template name */
  name?: string;
  /** template description */
  description?: string;
  /** component type */
  type?: ComponentType;
  /** template language */
  language?: ComponentLanguage;
}

export interface CreateCustomComponentRequest {
  'FlowDevops-Agw-UserId'?: string;
  space_id: Int64;
  /** Component information */
  component?: CustomComponent;
  'X-Jwt-Token'?: string;
  base?: base.Base;
}

export interface CreateCustomComponentResponse {
  component_id: Int64;
  base_resp?: base.BaseResp;
}

export interface CustomComponent {
  /** Component ID */
  id?: Int64;
  /** unique identifier */
  component_key?: string;
  /** Component name */
  display_name?: string;
  /** Component Description */
  description?: string;
  /** Component type */
  component_type?: ComponentType;
  /** creator ID */
  creator_id?: Int64;
  /** creation time */
  create_tsms?: Int64;
  /** update time */
  update_tsms?: Int64;
  /** state */
  status?: ComponentCreateStatus;
  /** version */
  version?: string;
  /** component implementation language */
  language?: ComponentLanguage;
  /** component icon */
  icon?: Icon;
  /** component warehouse address */
  repo?: string;
  /** Component Cloud IDE Workspace Information */
  workspace_info?: WorkspaceInfo;
}

export interface CustomComponentReleaseRecord {
  /** Component Release ID */
  release_id?: Int64;
  /** Component ID */
  component_id?: Int64;
  /** component version */
  component_version?: string;
  /** Component version corresponding codebase Tag */
  tag?: string;
  /** version description */
  description?: string;
  /** publisher */
  creator_id?: Int64;
  /** creation time */
  create_tsms?: Int64;
  /** update time */
  update_tsms?: Int64;
  /** release status */
  status?: ComponentReleaseStatus;
  /** error message */
  err_info?: ErrInfo;
}

export interface DeleteCustomComponentRequest {
  'FlowDevops-Agw-UserId'?: string;
  /** Space ID */
  space_id: Int64;
  /** Component ID */
  component_id: Int64;
  'X-Jwt-Token'?: string;
  base?: base.Base;
}

export interface DeleteCustomComponentResponse {
  base_resp?: base.BaseResp;
}

export interface ErrInfo {
  /** error code */
  code?: number;
  /** error message */
  message?: string;
  log_id?: string;
}

export interface GetCustomComponentReleaseRecordRequest {
  'FlowDevops-Agw-UserId'?: string;
  /** Space ID */
  space_id: Int64;
  /** Component ID */
  component_id: Int64;
  release_id: Int64;
  base?: base.Base;
}

export interface GetCustomComponentReleaseRecordResponse {
  /** Component version release information */
  release_record?: CustomComponentReleaseRecord;
  base_resp?: base.BaseResp;
}

export interface GetCustomComponentRequest {
  'FlowDevops-Agw-UserId'?: string;
  /** Space ID */
  space_id: Int64;
  /** Component ID */
  component_id: Int64;
  base?: base.Base;
}

export interface GetCustomComponentResponse {
  /** Component information */
  component?: CustomComponent;
  base_resp?: base.BaseResp;
}

export interface Icon {
  /** frontend -> backend */
  uri?: string;
  /** backend -> frontend */
  url?: string;
}

export interface IDELaunchRequest {
  'FlowDevops-Agw-UserId'?: string;
  /** Space ID */
  space_id: Int64;
  'X-Jwt-Token': string;
  base?: base.Base;
}

export interface IDELaunchResponse {
  /** Component Cloud IDE Workspace Information */
  workspace_info?: WorkspaceInfo;
  /** Do you have cloud ide permission? */
  has_auth?: boolean;
  base_resp?: base.BaseResp;
}

export interface IsComponentKeyValidRequest {
  'FlowDevops-Agw-UserId'?: string;
  /** Space ID */
  space_id: Int64;
  /** component identification */
  component_key: string;
  base?: base.Base;
}

export interface IsComponentKeyValidResponse {
  /** component_key is valid */
  is_valid?: boolean;
  base_resp?: base.BaseResp;
}

export interface ListComponentTemplateInfoRequest {
  'FlowDevops-Agw-UserId'?: string;
  /** Space ID */
  space_id: Int64;
  base?: base.Base;
}

export interface ListComponentTemplateInfoResponse {
  /** Component template information */
  component_templates?: Array<ComponentTemplateInfo>;
  base_resp?: base.BaseResp;
}

export interface ListCustomComponentReleaseRecordRequest {
  'FlowDevops-Agw-UserId'?: string;
  /** Space ID */
  space_id: Int64;
  /** Component ID */
  component_id: Int64;
  page?: Int64;
  page_size?: Int64;
  base?: base.Base;
}

export interface ListCustomComponentReleaseRecordResponse {
  component_release_records?: Array<CustomComponentReleaseRecord>;
  total?: Int64;
  base_resp?: base.BaseResp;
}

export interface ListCustomComponentRequest {
  'FlowDevops-Agw-UserId'?: string;
  /** Space ID */
  space_id: Int64;
  page?: Int64;
  page_size?: Int64;
  /** fuzzy search
Name/key fuzzy match */
  key_word?: string;
  /** creator ID */
  creator_i_d?: Int64;
  base?: base.Base;
}

export interface ListCustomComponentResponse {
  /** Component information */
  components?: Array<CustomComponent>;
  total?: Int64;
  base_resp?: base.BaseResp;
}

export interface ListSupportComponentTypeRequest {
  'FlowDevops-Agw-UserId'?: string;
  space_id: Int64;
  page?: Int64;
  page_size?: Int64;
  base?: base.Base;
}

export interface ListSupportComponentTypeResponse {
  /** component type */
  component_types?: Array<ComponentType>;
  total?: Int64;
  base_resp?: base.BaseResp;
}

export interface ReleaseCustomComponentRequest {
  /** Component ID */
  component_id: Int64;
  'FlowDevops-Agw-UserId'?: string;
  /** Space ID */
  space_id: Int64;
  /** Component version release information */
  component_release?: CustomComponentReleaseRecord;
  'X-Jwt-Token'?: string;
  base?: base.Base;
}

export interface ReleaseCustomComponentResponse {
  release_id: Int64;
  base_resp?: base.BaseResp;
}

export interface UpdateCustomComponentRequest {
  'FlowDevops-Agw-UserId'?: string;
  /** Space ID */
  space_id: Int64;
  /** Component ID */
  component_id: Int64;
  component?: CustomComponent;
  base?: base.Base;
}

export interface UpdateCustomComponentResponse {
  base_resp?: base.BaseResp;
}

export interface WorkspaceInfo {
  /** cloudide workspace id */
  workspace_id?: string;
  /** cloudide workspace url */
  workspace_url?: string;
  /** Workspace login status */
  workspace_launched?: boolean;
}
/* eslint-enable */
