/*
 * Copyright 2025 coze-dev Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
 
// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

export type Int64 = string | number;

/** Order status */
export enum OrderStatus {
  /** initialization */
  Init = 0,
  /** success */
  Success = 1,
  /** fail */
  Failed = 2,
  /** close */
  Closed = 3,
  /** Refund is in progress. */
  Refunding = 4,
  /** Refunded. */
  Refunded = 5,
  /** Refund failed. */
  RefundFaield = 6,
  /** Rejected */
  ChargeBack = 7,
  /** Refusal defense successful */
  ChargeBackReverse = 8,
}

/** Order type */
export enum OrderType {
  /** unknown */
  Unknown = 0,
  /** Token recharge */
  TokenCharge = 1,
  /** Token automatic recharge */
  TokenAutoCharge = 2,
  /** MessageCredit subscription */
  SubMessageCredit = 11,
  /** MessageCredit recharge */
  MessageCredit = 12,
}

export enum RefundType {
  Unknown = 0,
  /** Full refund */
  Full = 1,
  /** Refund per usage */
  ActualUse = 2,
}

export interface ByteDanceUser {
  /** email */
  email?: string;
  /** avatar */
  avatar_url?: string;
  /** Chinese name */
  name?: string;
  /** English */
  en_name?: string;
}

export interface PassportUser {
  /** user uid */
  uid?: string;
  /** nickname */
  name?: string;
  /** avatar */
  avatar_url?: string;
}
/* eslint-enable */
