/*
 * Copyright 2025 coze-dev Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
 
// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

import * as flow_devops_prompt_common from './flow_devops_prompt_common';
import * as base from './base';
import * as mcp from './mcp';

export type Int64 = string | number;

export interface ChatTestRequest {
  prompt: flow_devops_prompt_common.Prompt;
  message?: flow_devops_prompt_common.Message;
  contexts?: Array<flow_devops_prompt_common.Message>;
  variables?: Array<flow_devops_prompt_common.Variable>;
  /** Space ID */
  space_id: Int64;
  base?: base.Base;
}

export interface ChatTestResponse {
  item?: flow_devops_prompt_common.ReplyItem;
  code?: number;
  msg?: string;
  base_resp?: base.BaseResp;
}

export interface ExecuteBatchRequest {
  /** PromptID */
  prompt_id?: Int64;
  /** Space ID */
  space_id?: Int64;
  /** CaseID */
  case_id?: Int64;
  /** DatasetID */
  dataset_id?: Int64;
  /** RowGroupIDs */
  row_group_ids?: Array<Int64>;
  /** MCP dynamic configuration */
  mcp_execute_config?: mcp.MCPExecuteConfig;
  base?: base.Base;
}

export interface ExecuteBatchResponse {
  task_id?: Int64;
  code?: number;
  msg?: string;
  base_resp?: base.BaseResp;
}

export interface GetDebugDetailRequest {
  debug_id?: Int64;
  /** PromptID */
  prompt_id?: Int64;
  /** Space ID */
  space_id?: Int64;
  base?: base.Base;
}

export interface GetDebugDetailResponse {
  debug_detail?: flow_devops_prompt_common.DebugDetail;
  code?: number;
  msg?: string;
  base_resp?: base.BaseResp;
}

export interface GetMockContextRequest {
  /** Prompt Key */
  prompt_id: Int64;
  space_id: Int64;
  base?: base.Base;
}

export interface GetMockContextResponse {
  /** Deprecated using ContextsV2 */
  contexts?: Array<flow_devops_prompt_common.Message>;
  /** parameter list */
  variables?: Array<Array<flow_devops_prompt_common.Variable>>;
  /** user debug configuration */
  user_debug_config?: flow_devops_prompt_common.UserDebugConfig;
  /** arena configuration */
  compare_config?: flow_devops_prompt_common.CompareConfig;
  /** Dialogue history */
  contexts_v2?: Array<flow_devops_prompt_common.DebugMessage>;
  code?: number;
  msg?: string;
  base_resp?: base.BaseResp;
}

export interface ListDebugHistoryRequest {
  /** PromptID */
  prompt_id?: Int64;
  /** Space ID */
  space_id?: Int64;
  /** By default, only the debugging records of the logged-in user are displayed. If listAll is passed, all records are returned */
  list_all?: boolean;
  /** Start with null, scroll into NextCursor in Response */
  cursor?: Int64;
  /** The number of days, the default is 7 days if not passed on. */
  offset?: Int64;
  base?: base.Base;
}

export interface ListDebugHistoryResponse {
  /** Prompt list */
  debug_history?: Array<flow_devops_prompt_common.DebugBrief>;
  next_cursor?: Int64;
  has_more?: boolean;
  code?: number;
  msg?: string;
  base_resp?: base.BaseResp;
}

export interface LoadBatchDebugInfoRequest {
  /** PromptID */
  prompt_id?: Int64;
  /** Space ID */
  space_id?: Int64;
  base?: base.Base;
}

export interface LoadBatchDebugInfoResponse {
  case_id?: Int64;
  code?: number;
  msg?: string;
  base_resp?: base.BaseResp;
}

export interface SaveMockContextRequest {
  /** PromptID */
  prompt_id: Int64;
  /** Deprecated using ContextsV2 */
  contexts?: Array<flow_devops_prompt_common.Message>;
  /** Space ID */
  space_id: Int64;
  /** multiple sets of variables */
  variables?: Array<Array<flow_devops_prompt_common.Variable>>;
  /** user debug configuration */
  user_debug_config?: flow_devops_prompt_common.UserDebugConfig;
  /** arena configuration */
  compare_config?: flow_devops_prompt_common.CompareConfig;
  /** Dialogue history */
  contexts_v2?: Array<flow_devops_prompt_common.DebugMessage>;
  base?: base.Base;
}

export interface SaveMockContextResponse {
  code?: number;
  msg?: string;
  base_resp?: base.BaseResp;
}

export interface SendMessageRequest {
  prompt: flow_devops_prompt_common.Prompt;
  message?: flow_devops_prompt_common.Message;
  contexts?: Array<flow_devops_prompt_common.Message>;
  variables?: Array<flow_devops_prompt_common.Variable>;
  /** Space ID */
  space_id: Int64;
  /** Whether to step through debugging */
  single_step_debug?: boolean;
  /** Series debugging record (function call single step debugging) */
  debug_trace_key?: string;
  /** MCP dynamic configuration */
  mcp_execute_config?: mcp.MCPExecuteConfig;
  base?: base.Base;
}

export interface SendMessageResponse {
  item?: flow_devops_prompt_common.ReplyItem;
  debug_id?: string;
  code?: number;
  msg?: string;
  base_resp?: base.BaseResp;
}

export interface StreamingSendMessageRequest {
  prompt: flow_devops_prompt_common.Prompt;
  message?: flow_devops_prompt_common.Message;
  contexts?: Array<flow_devops_prompt_common.Message>;
  variables?: Array<flow_devops_prompt_common.Variable>;
  /** Space ID */
  space_id: Int64;
  /** Whether to step through debugging */
  single_step_debug?: boolean;
  /** Series debugging record (function call single step debugging) */
  debug_trace_key?: string;
  /** MCP dynamic configuration */
  mcp_execute_config?: mcp.MCPExecuteConfig;
  base?: base.Base;
}

export interface StreamingSendMessageResponse {
  item?: flow_devops_prompt_common.ReplyItem;
  debug_id?: string;
  code?: number;
  msg?: string;
  base_resp?: base.BaseResp;
}

export interface StreamingSendMessageWithoutPermissionCheckRequest {
  prompt: flow_devops_prompt_common.Prompt;
  message?: flow_devops_prompt_common.Message;
  contexts?: Array<flow_devops_prompt_common.Message>;
  variables?: Array<flow_devops_prompt_common.Variable>;
  /** Space ID */
  space_id: Int64;
  /** Whether to step through debugging */
  single_step_debug?: boolean;
  /** Series debugging record (function call single step debugging) */
  debug_trace_key?: string;
  /** MCP dynamic configuration */
  mcp_execute_config?: mcp.MCPExecuteConfig;
  base?: base.Base;
}

export interface StreamingSendMessageWithoutPermissionCheckResponse {
  item?: flow_devops_prompt_common.ReplyItem;
  code?: number;
  msg?: string;
  base_resp?: base.BaseResp;
}
/* eslint-enable */
