/*
 * Copyright 2025 coze-dev Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
 
// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

import * as flow_devops_prompt_common from './flow_devops_prompt_common';
import * as base from './base';

export type Int64 = string | number;

export interface AddSpaceMemberRequest {
  /** Space ID */
  space_id: Int64;
  /** Add space member */
  space_members?: Array<flow_devops_prompt_common.SpaceMember>;
  base?: base.Base;
}

export interface AddSpaceMemberResponse {
  code?: number;
  msg?: string;
  base_resp?: base.BaseResp;
}

export interface AuthComponentSDKRequest {
  /** A random string of numbers and letters */
  noncestr?: string;
  /** Timestamp (milliseconds) */
  timestamp?: Int64;
  /** Component page URL */
  url?: string;
  base?: base.Base;
}

export interface AuthComponentSDKResponse {
  signature?: string;
  code?: number;
  msg?: string;
  base_resp?: base.BaseResp;
}

export interface CreateSpaceRequest {
  /** space name */
  name: string;
  /** spatial description */
  description?: string;
  space_type?: flow_devops_prompt_common.SpaceType;
  base?: base.Base;
}

export interface CreateSpaceResponse {
  /** Create space */
  space?: flow_devops_prompt_common.Space;
  code?: number;
  msg?: string;
  base_resp?: base.BaseResp;
}

export interface GetSessionInfoRequest {
  base?: base.Base;
}

export interface GetSessionInfoResponse {
  /** Login user information */
  user_info?: flow_devops_prompt_common.UserInfo;
  code?: number;
  msg?: string;
  base_resp?: base.BaseResp;
}

export interface GetSpaceRequest {
  /** Space ID */
  space_id: Int64;
  base?: base.Base;
}

export interface GetSpaceResponse {
  /** space */
  space?: flow_devops_prompt_common.Space;
  code?: number;
  msg?: string;
  base_resp?: base.BaseResp;
}

export interface GetUserInfoRequest {
  /** Optional user ID */
  user_id?: string;
  /** Optional username */
  user_name?: string;
  base?: base.Base;
}

export interface GetUserInfoResponse {
  /** user information */
  user_info?: flow_devops_prompt_common.UserInfo;
  code?: number;
  msg?: string;
  base_resp?: base.BaseResp;
}

export interface GetUserSpaceRolesRequest {
  /** Space ID */
  space_id: Int64;
  base?: base.Base;
}

export interface GetUserSpaceRolesResponse {
  roles?: Array<flow_devops_prompt_common.AuthRole>;
  code?: number;
  msg?: string;
  base_resp?: base.BaseResp;
}

export interface LarkCardActionCallbackRequest {
  challenge?: string;
  schema?: string;
  header?: flow_devops_prompt_common.LarkCallbackHeader;
  event?: flow_devops_prompt_common.LarkCallbackEvent;
}

export interface LarkCardActionCallbackResponse {
  challenge?: string;
  toast?: flow_devops_prompt_common.LarkToast;
  card?: flow_devops_prompt_common.LarkCard;
  base_resp?: base.BaseResp;
}

export interface ListUserSpaceRequest {
  base?: base.Base;
}

export interface ListUserSpaceResponse {
  /** space list */
  spaces?: Array<flow_devops_prompt_common.Space>;
  code?: number;
  msg?: string;
  base_resp?: base.BaseResp;
}

export interface LoginRequest {
  /** login authorization code */
  code?: string;
  /** Login process redirect uri */
  state?: string;
  /** Specify sessionID */
  session_id?: string;
  base?: base.Base;
}

export interface LoginResponse {
  code?: number;
  msg?: string;
  base_resp?: base.BaseResp;
}

export interface LogoutRequest {
  base?: base.Base;
}

export interface LogoutResponse {
  code?: number;
  msg?: string;
  base_resp?: base.BaseResp;
}

export interface MCheckPermissionRequest {
  /** Authentication Triple List */
  auths?: Array<flow_devops_prompt_common.SubjectActionObjects>;
  /** Application ID, used to distinguish between internal and external fields
App ID */
  app_id?: number;
  base?: base.Base;
}

export interface MCheckPermissionResponse {
  auth_res?: Array<flow_devops_prompt_common.SubjectActionObjectAuthRes>;
  code?: number;
  msg?: string;
  base_resp?: base.BaseResp;
}

export interface MGetUserInfoRequest {
  /** Feishu UserID List */
  user_ids?: Array<string>;
  /** SsoUserName List */
  user_names?: Array<string>;
  base?: base.Base;
}

export interface MGetUserInfoResponse {
  /** user information list */
  user_infos?: Array<flow_devops_prompt_common.UserInfo>;
  code?: number;
  msg?: string;
  base_resp?: base.BaseResp;
}

export interface QuerySpaceMemberRequest {
  /** Space ID */
  space_id: Int64;
  role_type?: flow_devops_prompt_common.SpaceRoleType;
  page: number;
  page_size: number;
  base?: base.Base;
}

export interface QuerySpaceMemberResponse {
  /** space member */
  space_members?: Array<flow_devops_prompt_common.SpaceMember>;
  total?: number;
  /** Member-tenant distribution, deduplicated */
  member_tenant?: Array<flow_devops_prompt_common.TenantType>;
  code?: number;
  msg?: string;
  base_resp?: base.BaseResp;
}

export interface QueryUserInfoRequest {
  /** Username fuzzy search */
  name_like: string;
  /** Page size, default is 20 */
  page_size: number;
  /** Paging Token */
  page_token: string;
  base?: base.Base;
}

export interface QueryUserInfoResponse {
  /** user information list */
  user_infos?: Array<flow_devops_prompt_common.UserInfo>;
  /** Paging Token */
  page_token?: string;
  /** Is there a next page? */
  has_more?: boolean;
  code?: number;
  msg?: string;
  base_resp?: base.BaseResp;
}

export interface RemoveSpaceMemberRequest {
  /** Space ID */
  space_id: Int64;
  /** Remove space member */
  space_members?: Array<flow_devops_prompt_common.SpaceMember>;
  base?: base.Base;
}

export interface RemoveSpaceMemberResponse {
  code?: number;
  msg?: string;
  base_resp?: base.BaseResp;
}

export interface UpdateSpaceRequest {
  /** Space ID */
  space_id: Int64;
  /** space name */
  name?: string;
  /** spatial description */
  description?: string;
  /** release approval configuration */
  release_approval_config?: flow_devops_prompt_common.ReleaseApprovalConfig;
  base?: base.Base;
}

export interface UpdateSpaceResponse {
  code?: number;
  msg?: string;
  base_resp?: base.BaseResp;
}
/* eslint-enable */
