/*
 * Copyright 2025 coze-dev Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
 
// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

import * as base from './base';
import * as flow_devops_prompt_common from './flow_devops_prompt_common';
import * as mcp from './mcp';

export type Int64 = string | number;

export enum AccountMode {
  /** Use shared model account: limited viewership of the use of public limited viewership, can not guarantee stability */
  SharedAccount = 1,
  /** Use the independent model account applied by your own business: limit the configuration of independent accounts */
  CustomAccount = 2,
}

export enum Model {
  GPT35Turbo16k = 1,
}

export enum ReplyType {
  /** Final result */
  ReplyTypeFinalAnswer = 0,
}

export enum Role {
  RoleSystem = 0,
  RoleUser = 1,
  RoleAssistant = 2,
}

export enum StreamState {
  /** non-streaming */
  StreamStateNone = 0,
  /** Streaming starts (first packet) */
  StreamStateBegin = 1,
  /** streaming */
  StreamStateStreaming = 2,
  /** End of churn transfer (tail packet) */
  StreamStateEnd = 3,
}

export enum UsageScenario {
  Default = 1,
  Evaluation = 2,
  /** Prompt as a Service */
  PromptAsAService = 3,
  /** AI marking */
  AIAnnotate = 4,
  /** mass score */
  AIScore = 5,
  /** data label */
  AITag = 6,
}

export interface CustomAccount {
  /** Model name */
  model_name: string;
  /** model account */
  api_key: string;
  /** The account of the skyLark model needs additional ak/sk information. */
  sky_lark_account_extra?: SkyLarkAccountExtra;
  /** bot_engine connector_id (only seed models need to be passed) */
  connector_id?: Int64;
}

export interface EvalPromptVersionRequest {
  /** Prompt key */
  prompt_key: string;
  /** traffic identification */
  traffic: string;
  /** For fornax authentication */
  Authorization?: string;
  base?: base.Base;
}

export interface EvalPromptVersionResponse {
  /** Hit grey release */
  hit?: boolean;
  /** Back to version */
  version?: string;
  code?: number;
  msg?: string;
  base_resp?: base.BaseResp;
}

export interface ExecuteRequest {
  /** Just pass one PromptKey and PromptID. It is recommended to use your own defined PromptKey, which is more readable. */
  prompt_key?: string;
  prompt_id?: Int64;
  /** This field is scheduled to go offline, please do not pass the value. If you do not pass the value, use the latest released version. */
  version?: string;
  message?: flow_devops_prompt_common.Message;
  /** contextual information */
  contexts?: Array<flow_devops_prompt_common.Message>;
  /** variable */
  variables?: Array<flow_devops_prompt_common.Variable>;
  /** Account mode (shared account is used by default, but shared account does not guarantee stability. It is recommended to apply and use your own independent model account) */
  account_mode?: AccountMode;
  /** List of independent model accounts, account mode When selecting an independent account, you need to pass your own independent account information */
  custom_accounts?: Array<CustomAccount>;
  /** Whether to step through debugging */
  single_step_debug?: boolean;
  /** Series debugging record (function call single step debugging) */
  debug_trace_key?: string;
  /** usage scenario */
  usage_scenario?: UsageScenario;
  /** traffic identification */
  traffic?: string;
  /** Request additional parameters */
  request_extra?: RequestExtra;
  /** Custom model parameters (passing this parameter overrides the model parameters) */
  custom_model_config?: flow_devops_prompt_common.ModelConfig;
  /** release tag */
  release_label?: string;
  /** MCP dynamic configuration */
  mcp_execute_config?: mcp.MCPExecuteConfig;
  /** For fornax authentication */
  token?: string;
  /** It is used to identify the identity of the old user and go offline after the user is migrated. */
  'Agw-Auth'?: string;
  /** For fornax authentication */
  Authorization?: string;
  base?: base.Base;
}

export interface ExecuteResponse {
  item?: flow_devops_prompt_common.ReplyItem;
  code?: number;
  msg?: string;
  base_resp?: base.BaseResp;
}

export interface MPullPromptQuery {
  /** Prompt key */
  prompt_key: string;
  /** version */
  version?: string;
  /** Publish label */
  release_label?: string;
}

export interface MPullPromptRequest {
  /** Prompt query */
  prompt_queries: Array<MPullPromptQuery>;
  /** encryption options */
  encrypt_option?: flow_devops_prompt_common.PromptEncryptOption;
  /** For fornax authentication */
  token?: string;
  /** It is used to identify the identity of the old user and go offline after the user is migrated. */
  'Agw-Auth'?: string;
  /** For fornax authentication */
  Authorization?: string;
  base?: base.Base;
}

export interface MPullPromptResponse {
  /** Back to Prompt List */
  prompts?: Array<flow_devops_prompt_common.Prompt>;
  code?: number;
  msg?: string;
  base_resp?: base.BaseResp;
}

export interface RequestExtra {
  /** GPTOpenAPI platform extra parameters */
  gpt_openapi_extra?: string;
}

export interface SkyLarkAccountExtra {
  ak: string;
  sk: string;
}

export interface StreamingExecuteRequest {
  /** Just pass one PromptKey and PromptID. It is recommended to use your own defined PromptKey, which is more readable. */
  prompt_key?: string;
  prompt_id?: Int64;
  /** This field is scheduled to go offline, please do not pass the value. If you do not pass the value, use the latest released version. */
  version?: string;
  message?: flow_devops_prompt_common.Message;
  /** contextual information */
  contexts?: Array<flow_devops_prompt_common.Message>;
  /** variable */
  variables?: Array<flow_devops_prompt_common.Variable>;
  /** Account mode (shared account is used by default, but shared account does not guarantee stability. It is recommended to apply and use your own independent model account) */
  account_mode?: AccountMode;
  /** List of independent model accounts, account mode When selecting an independent account, you need to pass your own independent account information */
  custom_accounts?: Array<CustomAccount>;
  /** Whether to step through debugging */
  single_step_debug?: boolean;
  /** Series debugging record (function call single step debugging) */
  debug_trace_key?: string;
  /** usage scenario */
  usage_scenario?: UsageScenario;
  /** traffic identification */
  traffic?: string;
  /** Request additional parameters */
  request_extra?: RequestExtra;
  /** Custom model parameters (passing this parameter overrides the model parameters) */
  custom_model_config?: flow_devops_prompt_common.ModelConfig;
  /** release tag */
  release_label?: string;
  /** MCP dynamic configuration */
  mcp_execute_config?: mcp.MCPExecuteConfig;
  /** For fornax authentication */
  token?: string;
  /** It is used to identify the identity of the old user and go offline after the user is migrated. */
  'Agw-Auth'?: string;
  /** For fornax authentication */
  Authorization?: string;
  base?: base.Base;
}

export interface StreamingExecuteResponse {
  item?: flow_devops_prompt_common.ReplyItem;
  code?: number;
  msg?: string;
  base_resp?: base.BaseResp;
}
/* eslint-enable */
