/*
 * Copyright 2025 coze-dev Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
 
// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

export type Int64 = string | number;

/** Access to the general structure introduced by agw's public parameter (ClientIp), copy from  */
export interface UnifyArgs {
  platform_id?: number;
  is_ios?: boolean;
  is_android?: boolean;
  access_type?: number;
  resolution_width?: number;
  resolution_height?: number;
  unify_version_code?: Int64;
  unify_version_code_611?: Int64;
  product_id?: number;
  region?: Int64;
  app_cn_name?: string;
  app_name?: string;
  /** From "aid" or "app_id" in query */
  app_id?: number;
  /** From the "install_id" in the cookie or the "iid" of the query */
  install_id?: Int64;
  /** The "device_id" from the query, or from the device_info service based on install_id device_id */
  device_id?: Int64;
  /** The IP closest to the user, get the logical reference:  */
  client_ip?: string;
}
/* eslint-enable */
