/*
 * Copyright 2025 coze-dev Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
 
// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

export type Int64 = string | number;

/** *************************** audit ********************************* */
export enum AuditStatus {
  /** Under review. */
  Auditing = 0,
  /** approved */
  Success = 1,
  /** moderation failed */
  Failed = 2,
}

/** *************************** publish ********************************* */
export enum ConnectorDynamicStatus {
  Normal = 0,
  Offline = 1,
  TokenDisconnect = 2,
}

export enum FolderType {
  /** Project/Agent Folder */
  App = 1,
  /** resource folder */
  Resource = 2,
}

export enum OrderByType {
  Asc = 1,
  Desc = 2,
}

export enum PermissionType {
  /** Can't view details */
  NoDetail = 1,
  /** You can check the details. */
  Detail = 2,
  /** Can be viewed and operated */
  Operate = 3,
}

export enum ResourceType {
  Plugin = 1,
  Workflow = 2,
  Imageflow = 3,
  Knowledge = 4,
  UI = 5,
  Prompt = 6,
  Database = 7,
  Variable = 8,
}

export enum SpaceStatus {
  Valid = 1,
  Invalid = 2,
}

/** Audit results */
export interface AuditData {
  /** True: The machine verification failed */
  check_not_pass?: boolean;
  /** The machine audit verification failed the copy. */
  check_not_pass_msg?: string;
}

export interface AuditInfo {
  audit_status?: AuditStatus;
  publish_id?: string;
  commit_version?: string;
}

export interface ConnectorInfo {
  id?: string;
  name?: string;
  icon?: string;
  connector_status?: ConnectorDynamicStatus;
  share_link?: string;
}

export interface FolderBasicInfo {
  id?: string;
  /** Parent folder id */
  parent_id?: string;
  /** Folder type */
  folder_type?: FolderType;
  name?: string;
  description?: string;
  space_id?: string;
  creator_id?: string;
  /** Creation time, second timestamp */
  create_time?: string;
  /** Update time, second timestamp */
  update_time?: string;
  /** Whether to delete */
  is_deleted?: boolean;
}

export interface FolderInfo {
  folder_basic_info?: FolderBasicInfo;
  /** List of subfolders, only the tree interface is returned */
  children_list?: Array<FolderInfo>;
  /** Parent folder path, does not contain this folder */
  parent_path?: Array<FolderBasicInfo>;
  /** Parent folder path, including this folder */
  full_path?: Array<FolderBasicInfo>;
  /** Folder creator information */
  folder_creator_info?: User;
}

export interface Space {
  id?: Int64;
  owner_id?: Int64;
  status?: SpaceStatus;
  name?: string;
}

export interface User {
  user_id?: string;
  /** user nickname */
  nickname?: string;
  /** user avatar */
  avatar_url?: string;
  /** user name */
  user_unique_name?: string;
  /** user tag */
  user_label?: UserLabel;
}

/** *************************** user ********************************* */
export interface UserLabel {
  label_id?: string;
  label_name?: string;
  icon_uri?: string;
  icon_url?: string;
  jump_link?: string;
}

export interface Variable {
  /** variable name */
  keyword?: string;
  /** default value */
  default_value?: string;
  /** Variable type */
  variable_type?: string;
  /** Variable source */
  channel?: string;
  /** variable description */
  description?: string;
  /** Whether to enable */
  enable?: boolean;
  /** Variables support access in Prompt by default. After unchecking, access in Prompt will not be supported (only accessible in Workflow) */
  prompt_enable?: boolean;
}
/* eslint-enable */
