/*
 * Copyright 2025 coze-dev Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
 
// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

export type Int64 = string | number;

export enum ConnectorAuditStatus {
  /** Unknown, Unaudited */
  Unknown = 0,
  /** Under review. */
  Progress = 1,
  /** approved */
  Audited = 2,
  /** moderation rejection */
  Reject = 3,
}

export enum ConnectorBindStatus {
  Invalid = 0,
  Valid = 1,
  SaveNotPublish = 2,
  /** Token changes */
  Disconnected = 3,
  /** The current configuration is invalid and needs to be reconfigured. Currently only Bitable */
  NeedReconfigure = 4,
}

export enum ConnectorBindType {
  /** No binding required */
  NoBindRequired = 1,
  /** Auth binding */
  AuthBind = 2,
  /** Kv binding */
  KvBind = 3,
  /** Kv and Auth authorization */
  KvAuthBind = 4,
  /** API channel binding */
  ApiBind = 5,
  /** WebSDK binding */
  WebSDKBind = 6,
  /** store binding */
  StoreBind = 7,
  /** One button each for authorization and configuration */
  AuthAndConfig = 8,
  /** template channel binding */
  TemplateBind = 9,
}

export enum ConnectorClassification {
  /** API or SDK */
  APIOrSDK = 1,
  /** social platform */
  SocialPlatform = 2,
  /** Coze Shop/Template */
  Coze = 3,
  /** Mini Program */
  MiniProgram = 4,
  /** MCP Extension Library */
  CozeSpaceExtensionLibrary = 5,
}

export enum ConnectorStatus {
  /** Normal */
  Normal = 0,
  /** Under review. */
  InReview = 1,
  /** offline */
  Offline = 2,
}
/* eslint-enable */
