/*
 * Copyright 2025 coze-dev Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
 
// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

export type Int64 = string | number;

export enum PublishResult {
  /** unpublished */
  Default = 0,
  /** Under review. */
  Auditing = 1,
  /** Published successfully */
  Successful = 2,
  /** publish failed */
  Failed = 3,
}

export enum PublishStatus {
  /** Packing */
  Packing = 0,
  /** Packaging failed */
  PackFailed = 1,
  /** Under review. */
  Auditing = 2,
  /** review disapproved */
  AuditNotPass = 3,
  /** Channel is being released. */
  ConnectorPublishing = 4,
  /** release complete */
  PublishDone = 5,
}
/* eslint-enable */
