/*
 * Copyright 2025 coze-dev Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
 
// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

export type Int64 = string | number;

export enum ModelType {
  /** custom model */
  CustomModel = 1,
  /** basic model */
  FoundationModel = 2,
}

export enum OutPutStatus {
  Available = 1,
  Exported = 2,
  Expired = 3,
}

export enum TuningTaskStatus {
  UnKnown = 0,
  /** initialization */
  Init = 1,
  /** pre-check */
  Preprocessing = 2,
  /** in line */
  Queued = 3,
  /** Deploying */
  Deploying = 4,
  /** in progress */
  Running = 5,
  /** Finishing */
  Completing = 6,
  /** execution complete */
  Completed = 7,
  /** Terminating */
  Terminating = 8,
  /** termination of execution */
  Terminated = 9,
  /** execution failed */
  Failed = 10,
  /** EndPoint Scheduling */
  EndPointScheduling = 11,
  /** EndPoint is in use */
  EndPointRunning = 12,
  /** EndPoint deployment failed */
  EndPointDeployAbnormal = 14,
  /** task deletion */
  TaskDelete = 16,
}

/** training type */
export enum TuningType {
  FinetuneSft = 1,
  FunetuneLoRA = 2,
  Pretrain = 3,
  DPOLoRA = 4,
}

export enum ValidationType {
  /** Upload file */
  Upload = 1,
  /** Training dataset segmentation */
  TrainingCut = 2,
  /** No validation set */
  None = 3,
}
/* eslint-enable */
