/*
 * Copyright 2025 coze-dev Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
 
// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

import * as common_struct from './common_struct';

export type Int64 = string | number;

export enum FinetuneParamType {
  BatchSize = 1,
  LearningRate = 2,
  Epochs = 3,
}

export enum ModelClass {
  GPT = 1,
  SEED = 2,
  Claude = 3,
  /** name: MiniMax */
  MiniMax = 4,
  Plugin = 5,
  StableDiffusion = 6,
  ByteArtist = 7,
  Maas = 9,
  /** Abandoned: Qianfan (Baidu Cloud) */
  QianFan = 10,
  /** name：Google Gemini */
  Gemini = 11,
  /** name: Moonshot */
  Moonshot = 12,
  /** Name: Zhipu */
  GLM = 13,
  /** Name: Volcano Ark */
  MaaSAutoSync = 14,
  /** Name: Tongyi Qianwen */
  QWen = 15,
  /** name: Cohere */
  Cohere = 16,
  /** Name: Baichuan Intelligent */
  Baichuan = 17,
  /** Name: ERNIE Bot */
  Ernie = 18,
  /** Name: Magic Square */
  DeekSeek = 19,
  /** name: Llama */
  Llama = 20,
  StepFun = 23,
  Other = 999,
}

export enum ModelParamType {
  Float = 1,
  Int = 2,
  Boolean = 3,
  String = 4,
}

export enum ModelStatus {
  Online = 1,
  Offline = 2,
  Deleted = 3,
  FineTuneInQueue = 4,
  FineTuneRunning = 5,
  FineTuneFailed = 6,
  FineTuneTeminated = 7,
}

/** enum ModelTypeTag {
    MultiModal = 1//multimodaltimodal
    TextGenerate = 2//Text Generate generation
    Finetune = 3//trimmerne-tuning
}

enum ModelUserRightTag {
    Free = 1//Freeee
    New = 2//new model model
    Expiring = 3//will be removed soont to be removed from the shelves
    Premium = 4//Premiumvanced
}

enum ModelFeatureTag {
    HighSpeed = 1//High Speedgh speed
    CostEffective = 2//ce/performance ratio
    LongText = 3//long textg text
    CodeExpert = 4//Code Specialization Specialization
    ImageUnderstanding = 5//Image Understandinge understanding
    AudioUnderstanding = 6//Audio Understandingo comprehension
    VideoUnderstanding = 7//Video Understandingo understanding
}

enum ModelFunctionTag {
    TextGenerate = 1//Text Generate generation
    CodeGenerate = 2//code generation generation
    CodeUnderstanding = 3//Code Understanding understanding
    ImageUnderstanding = 4//Image Understandinge understanding
    AudioUnderstanding = 5//Audio Understandingo comprehension
    VideoUnderstanding = 6//Video Understandingo understanding
} */
export enum ModelTagClass {
  ModelType = 1,
  ModelUserRight = 2,
  ModelFeature = 3,
  ModelFunction = 4,
  ModelScenario = 5,
  ModelPayment = 15,
  /** model runtime capability */
  ModelAbility = 16,
  /** Do not do this issue */
  Custom = 20,
}

export enum OperateFinetuneTaskAction {
  stop = 1,
  resume = 2,
  delete = 3,
}

export enum OrderBy {
  /** comprehensive recommendation */
  Recommend = 1,
}

export enum ValidatingType {
  /** upload */
  upload = 1,
  /** Training dataset segmentation */
  TrainingSetSplit = 2,
}

export interface CreateFinetuneTaskData {
  task_id?: string;
}

export interface CreateFinetuneTaskRequest {
  space_id?: string;
  base_model_id?: string;
  /** training dataset */
  training_dataset_id?: string;
  /** validation set */
  validating_dataset?: ValidatingDataset;
  /** training configuration */
  finetune_configuration?: FinetuneConfiguration;
  description?: string;
  name?: string;
}

export interface CreateFinetuneTaskResponse {
  data?: CreateFinetuneTaskData;
  code?: Int64;
  msg?: string;
}

export interface DeleteFinetuneModelRequest {
  model_id?: string;
  space_id?: string;
}

export interface DeleteFinetuneModelResponse {
  code?: Int64;
  msg?: string;
}

export interface ExpansionTpmData {
  record_id?: string;
}

export interface ExpansionTpmRequest {
  model_id?: string;
  enterprise_id?: string;
  organization_id?: string;
  tpm_input_expansion?: string;
  tpm_output_expansion?: string;
  /** Effective time */
  start_time?: string;
  /** End effective time */
  end_time?: string;
}

export interface ExpansionTpmResponse {
  data?: ExpansionTpmData;
  code?: Int64;
  msg?: string;
}

export interface FinetuneConfiguration {
  /** batch size */
  batch_size?: Int64;
  /** training rounds */
  epochs?: Int64;
  /** learning rate */
  learning_rate?: number;
}

export interface FinetuneParam {
  type?: FinetuneParamType;
  name?: string;
  min?: string;
  max?: string;
  option_values?: Array<string>;
  is_activated?: boolean;
}

export interface FinetuneTemplateDatasets {
  zip_files?: string;
}

export interface FinetuneTrainingInfo {
  /** specific data */
  metric_data?: Array<FinetuneTrainingInfoItem>;
  /** indicator name */
  metric_name?: string;
}

export interface FinetuneTrainingInfoItem {
  /** abscissa */
  step?: Int64;
  /** ordinate */
  value?: number;
}

export interface GetEstimatedTpmExpansionCostData {
  estimated_cost?: number;
}

export interface GetEstimatedTpmExpansionCostRequest {
  model_id?: string;
  enterprise_id?: string;
  input_tpm?: string;
  output_tpm?: string;
}

export interface GetEstimatedTpmExpansionCostResponse {
  data?: GetEstimatedTpmExpansionCostData;
  code?: Int64;
  msg?: string;
}

export interface GetEstimatedTpmExpansionData {
  /** Input TPM expansion value */
  tpm_input_expansion?: Int64;
  /** Output TPM expansion value */
  tpm_output_expansino?: Int64;
}

export interface GetEstimatedTpmExpansionRequest {
  model_id?: string;
  enterprise_id?: string;
  estimated_rpm?: string;
  /** Effective time */
  StartTime?: string;
  /** End effective time */
  EndTime?: string;
}

export interface GetEstimatedTpmExpansionResponse {
  data?: GetEstimatedTpmExpansionData;
  code?: Int64;
  msg?: string;
}

export interface GetEstimatedTrainingCostData {
  cost?: number;
  token?: Int64;
  unit_cost?: number;
  epocs?: Int64;
  has_finish?: boolean;
}

export interface GetEstimatedTrainingCostRequest {
  task_id?: string;
  space_id?: string;
  base_model_id?: string;
  epochs?: Int64;
}

export interface GetEstimatedTrainingCostResponse {
  data?: GetEstimatedTrainingCostData;
  code?: Int64;
  msg?: string;
}

export interface GetFinetuneTemplateDatasetRequest {}

export interface GetFinetuneTemplateDatasetResponse {
  data?: FinetuneTemplateDatasets;
  code?: Int64;
  msg?: string;
}

export interface GetFinetuneTrainingInfoData {
  data_list?: Array<FinetuneTrainingInfo>;
}

export interface GetFinetuneTrainingInfoRequest {
  space_id?: string;
  model_id?: string;
}

export interface GetFinetuneTrainingInfoResponse {
  data?: GetFinetuneTrainingInfoData;
  code?: Int64;
  msg?: string;
}

export interface GetModelConcurrencyPerformanceDataRequest {
  space_id?: string;
  model_id?: string;
}

export interface GetModelConcurrencyPerformanceDataResponse {
  data?: ModelConcurrencyPerformance;
  code?: Int64;
  msg?: string;
}

export interface GetModelInfoData {
  model_info?: ModelInfo;
  model_owner?: common_struct.User;
}

export interface GetModelInfoRequest {
  space_id?: string;
  model_id?: string;
  is_finetuning?: boolean;
}

export interface GetModelInfoResponse {
  data?: GetModelInfoData;
  code?: Int64;
  msg?: string;
}

export interface GetModelListData {
  model_list?: Array<ModelListCard>;
  next_cursor_id?: string;
  has_more?: boolean;
  total?: Int64;
}

export interface GetModelListFilterParamsData {
  tag_filters?: Partial<Record<ModelTagClass, Array<string>>>;
  context_len_min?: Int64;
  context_len_max?: Int64;
  model_cost_min?: Int64;
  model_cost_max?: Int64;
  model_vendors?: Array<string>;
  model_ability?: ModelAbility;
  model_show_family_list?: Array<ModelShowFamily>;
}

export interface GetModelListFilterParamsRequest {}

export interface GetModelListFilterParamsResponse {
  data?: GetModelListFilterParamsData;
  code?: Int64;
  msg?: string;
}

export interface GetModelListRequest {
  space_id?: string;
  name?: string;
  tag_filters?: Partial<Record<ModelTagClass, Array<string>>>;
  context_len_min?: Int64;
  context_len_max?: Int64;
  model_cost_min?: Int64;
  model_cost_max?: Int64;
  model_vendor?: string;
  statusList?: Array<ModelStatus>;
  model_show_family_id?: string;
  order_by?: OrderBy;
  cursor_id?: string;
  limit?: number;
}

export interface GetModelListResponse {
  data?: GetModelListData;
  code?: Int64;
  msg?: string;
}

export interface GetModelPerformanceData {
  output_speed?: Array<ModelPerformance>;
  latency?: Array<ModelPerformance>;
  accuracy?: Array<ModelPerformance>;
}

export interface GetModelPerformanceDataRequest {
  space_id?: string;
  model_id?: string;
}

export interface GetModelPerformanceDataResponse {
  data?: GetModelPerformanceData;
  code?: Int64;
  msg?: string;
}

export interface GetModelUsageDataRequest {
  space_id?: string;
  model_id?: string;
}

export interface GetModelUsageDataResponse {
  data?: ModelUsageData;
  code?: Int64;
  msg?: string;
}

export interface GetSpaceModelUserConfigData {
  space_model_user_config_list?: Array<SpaceModelUserConfig>;
}

export interface GetSpaceModelUserConfigRequest {
  space_id?: string;
}

export interface GetSpaceModelUserConfigResponse {
  data?: GetSpaceModelUserConfigData;
  code?: Int64;
  msg?: string;
}

export interface ModelAbility {
  /** Do you want to show cot? */
  cot_display?: boolean;
  /** Supports function calls */
  function_call?: boolean;
  /** Does it support picture understanding? */
  image_understanding?: boolean;
  /** Does it support video understanding? */
  video_understanding?: boolean;
  /** Does it support audio understanding? */
  audio_understanding?: boolean;
  /** Whether to support continuation */
  prefill_resp?: boolean;
}

export interface ModelBasicInfo {
  name?: string;
  model_id?: string;
  model_class?: ModelClass;
  /** domain_model url of thrift icon */
  model_icon?: string;
  model_input_price?: number;
  model_output_price?: number;
  token_limit?: number;
  model_name?: string;
  model_class_name?: string;
  model_desc?: string;
  param_size?: string;
  /** Ark model node name */
  endpoint_name?: string;
  model_tags?: Partial<Record<ModelTagClass, Array<string>>>;
  /** Model manufacturer */
  model_vendor?: string;
  /** model parameters */
  model_params?: Array<ModelParameter>;
  show_family_id?: string;
  model_ability?: ModelAbility;
  default_model_flag?: boolean;
  /** 0-User visible 1-User invisible */
  model_config_type?: number;
  online_time?: string;
  offline_time?: string;
  status?: ModelStatus;
  update_time?: string;
}

export interface ModelConcurrencyPerformance {
  input_tmp_1d?: Array<ModelPerformance>;
  output_tmp_1d?: Array<ModelPerformance>;
  rpm_1d?: Array<ModelPerformance>;
  input_tmp_30d?: Array<ModelPerformance>;
  output_tmp_30d?: Array<ModelPerformance>;
  rpm_30d?: Array<ModelPerformance>;
  /** The number of times the daily peak exceeds the rpm threshold in a month */
  exceed_rpm_threshold_num?: Int64;
  /** The number of times the daily peak exceeds the tpm threshold in a month */
  exceed_tpm_threshold_num?: Int64;
}

export interface ModelConcurrentInfo {
  /** Is the TPM expansion effective? */
  has_model_tpm_expansion?: boolean;
  /** Can TPM be scaled (only models that can be scaled with TPM can) */
  can_model_tpm_expansion?: boolean;
  /** Whether to show concurrency model monitoring */
  show_model_concurrent_monitor?: boolean;
}

export interface ModelInfo {
  model_basic_info?: ModelBasicInfo;
  model_rate_limit?: ModelRateLimit;
  model_speed?: Int64;
  model_permission_info?: ModelPermissionInfo;
  finetune_params?: Partial<Record<FinetuneParamType, FinetuneParam>>;
  model_concurrent_info?: ModelConcurrentInfo;
}

export interface ModelListCard {
  model_basic_info?: ModelBasicInfo;
  model_permission_info?: ModelPermissionInfo;
  model_speed?: Int64;
  is_finetuning?: boolean;
}

export interface ModelParamClass {
  /** 1="Generation diversity", 2="Input and output length", 3="Output format" */
  class_id?: number;
  label?: string;
}

export interface ModelParamDefaultValue {
  default_val: string;
  creative?: string;
  balance?: string;
  precise?: string;
}

export interface ModelParameter {
  /** Configuration fields, such as max_tokens */
  name: string;
  /** Configure field display name */
  label?: string;
  /** Configuration field detail description */
  desc?: string;
  /** type */
  type: ModelParamType;
  /** Numerical type parameters, the minimum value allowed to be set */
  min?: string;
  /** Numerical type parameter, the maximum value allowed to be set */
  max?: string;
  /** Precision of float type parameters */
  precision?: number;
  /** Parameter default {"default": xx, "creative": xx} */
  default_val: ModelParamDefaultValue;
  /** Enumeration values such as response_format support text, markdown, json */
  options?: Array<Option>;
  /** Parameter classification, "Generation diversity", "Input and output length", "Output format" */
  param_class?: ModelParamClass;
}

export interface ModelPerformance {
  data?: number;
  time?: string;
}

export interface ModelPermissionInfo {
  can_delete?: boolean;
  can_finetune?: boolean;
  can_stop_tune_task?: boolean;
  can_retry_tune_task?: boolean;
  need_show_finetune_attention?: boolean;
}

export interface ModelRateLimit {
  qpm?: number;
  tpm?: number;
}

export interface ModelShowFamily {
  id?: string;
  icon?: string;
  iconUrl?: string;
  name?: string;
  ranking?: number;
}

export interface ModelUsage {
  BotTotalInput?: Int64;
  BotTotalOutput?: Int64;
  WorkflowTotalInput?: Int64;
  WorkflowTotalOutput?: Int64;
  date?: string;
}

export interface ModelUsageData {
  usage?: Array<ModelUsage>;
}

export interface OperateFinetuneTaskData {
  id?: string;
  status?: ModelStatus;
}

export interface OperateFinetuneTaskRequest {
  id?: string;
  /** Operation, stop, resume, delete */
  action?: OperateFinetuneTaskAction;
}

export interface OperateFinetuneTaskResponse {
  data?: OperateFinetuneTaskData;
  code?: Int64;
  msg?: string;
}

export interface Option {
  /** The value displayed by the option */
  label?: string;
  /** Filled in value */
  value?: string;
}

export interface SpaceModelUserConfig {
  space_id?: string;
  model_id?: string;
  config_type?: number;
}

export interface StartEstimatedTrainingCostData {
  task_id?: string;
}

export interface StartEstimatedTrainingCostRequest {
  base_model_id?: string;
  space_id?: string;
  training_dataset_id?: string;
  epochs?: Int64;
}

export interface StartEstimatedTrainingCostResponse {
  data?: StartEstimatedTrainingCostData;
  code?: Int64;
  msg?: string;
}

export interface UpdateModelConfigTypeRequest {
  space_id?: string;
  model_id?: string;
  /** 0-User visible 1-User invisible */
  config_type?: number;
}

export interface UpdateModelConfigTypeResponse {
  code?: Int64;
  msg?: string;
}

export interface UploadFinetuneDatasetData {
  dataset_id?: string;
}

export interface UploadFinetuneDatasetRequest {
  space_id?: string;
  /** File type, suffix */
  fileType?: string;
  /** file name */
  fileName?: string;
  data?: string;
  testing_data?: Blob;
}

export interface UploadFinetuneDatasetResponse {
  data?: UploadFinetuneDatasetData;
  code?: Int64;
  msg?: string;
}

export interface ValidatingDataset {
  validating_type?: ValidatingType;
  /** Split ratio, if it is a training dataset split pass 0 -100 */
  split_ratio?: Int64;
  validating_dataset_id?: string;
}
/* eslint-enable */
