/*
 * Copyright 2025 coze-dev Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
 
// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

import * as flow_devops_fornaxob_common from './flow_devops_fornaxob_common';
import * as annotation from './annotation';
import * as base from './base';
import * as eval_set from './eval_set';
import * as task from './task';
import * as datasetv2 from './datasetv2';
import * as flow_devops_fornaxob_fieldfilter from './flow_devops_fornaxob_fieldfilter';
import * as flow_devops_fornaxob_fieldfilterv2 from './flow_devops_fornaxob_fieldfilterv2';
import * as span from './span';

export type Int64 = string | number;

export enum ExportType {
  AppendData = 1,
  OverwriteData = 2,
}

export enum ItemStatus {
  Success = 0,
  Error = 1,
}

export enum SearchTraceType {
  LogID = 1,
  TraceID = 2,
  MessageID = 3,
  UID = 4,
}

export enum SearchTraceV3Type {
  LogID = 1,
  TraceID = 2,
}

export interface AnnotationEvaluator {
  evaluator_version_id: Int64;
  evaluator_name: string;
  evaluator_version: string;
}

export interface BatchGetTracesAdvanceInfoData {
  traces_advance_info: Array<TraceAdvanceInfo>;
}

export interface BatchGetTracesAdvanceInfoRequest {
  space_id: string;
  traces: Array<TraceQueryParams>;
  target_env?: flow_devops_fornaxob_common.EnvType;
  transferred?: boolean;
  'x-boe-env'?: string;
  /** Platform type, if left blank, the default is fornax. */
  platform_type?: flow_devops_fornaxob_common.PlatformType;
}

export interface BatchGetTracesAdvanceInfoResponse {
  data: BatchGetTracesAdvanceInfoData;
  /** Only for http requests; internal RPC is not used, unified access to Code and Msg through BaseResp */
  code?: number;
  /** Only for http requests; internal RPC is not used, unified access to Code and Msg through BaseResp */
  msg?: string;
}

export interface ChangeEvaluatorScoreRequest {
  workspace_id: Int64;
  evaluator_record_id: Int64;
  span_id: string;
  start_time: Int64;
  correction: annotation.Correction;
  Base?: base.Base;
}

export interface ChangeEvaluatorScoreResponse {
  annotation: annotation.Annotation;
  /** Only for http requests; internal RPC is not used, unified access to Code and Msg through BaseResp */
  code?: number;
  /** Only for http requests; internal RPC is not used, unified access to Code and Msg through BaseResp */
  msg?: string;
}

export interface EvaluationSetConfig {
  /** Is it a new review set? */
  is_new_evaluation_set: boolean;
  /** Evaluation set id, can be empty when adding a evaluation set */
  evaluation_set_id?: Int64;
  /** Review set name, can be empty when selecting an existing review set */
  evaluation_set_name?: string;
  /** Evaluating the tabular data schema */
  evaluation_set_schema?: eval_set.EvaluationSetSchema;
}

export interface ExportTracesToEvaluationRequest {
  space_id: string;
  spans: Array<string>;
  datasets: Array<string>;
  start_time?: string;
  end_time?: string;
  /** Platform type, if left blank, the default is fornax. */
  platform_type?: flow_devops_fornaxob_common.PlatformType;
  /** Platform type, if left blank, the default is fornax. */
  span_list_type?: flow_devops_fornaxob_common.SpanListType;
}

export interface ExportTracesToEvaluationResponse {
  /** Only for http requests; internal RPC is not used, unified access to Code and Msg through BaseResp */
  code?: number;
  /** Only for http requests; internal RPC is not used, unified access to Code and Msg through BaseResp */
  msg?: string;
}

export interface ExportTracesToEvaluationSetRequest {
  workspace_id: Int64;
  span_ids: Array<string>;
  evaluation_set: EvaluationSetConfig;
  start_time?: Int64;
  end_time?: Int64;
  /** Platform type, if left blank, the default is fornax. */
  platform_type?: flow_devops_fornaxob_common.PlatformType;
  /** Import method, if not filled in, the default is append. */
  export_type?: ExportType;
  field_mappings?: Array<task.FieldMapping>;
}

export interface ExportTracesToEvaluationSetResponse {
  /** Number of successful imports */
  success_count?: number;
  /** error message */
  errors?: Array<datasetv2.ItemErrorGroup>;
  /** review set id */
  evaluation_set_id?: Int64;
  /** review set name */
  evaluation_set_name?: string;
  /** Only for http requests; internal RPC is not used, unified access to Code and Msg through BaseResp */
  code?: number;
  /** Only for http requests; internal RPC is not used, unified access to Code and Msg through BaseResp */
  msg?: string;
}

/** You need to migrate to threadservice later. FieldMeta */
export interface FieldMeta {
  /** field type */
  value_type: flow_devops_fornaxob_common.ValueType;
  /** Supported operation types */
  filter_types: Array<flow_devops_fornaxob_fieldfilter.FieldFilterType>;
  /** Supported options */
  field_options?: flow_devops_fornaxob_fieldfilter.FieldOptions;
  /** Support custom filling in */
  support_customizable_option?: boolean;
  /** Supported operation types v2 */
  filter_types_v2?: Array<flow_devops_fornaxob_fieldfilterv2.FieldFilterType>;
}

export interface GetSpanInfoRequest {
  /** space id */
  space_id: string;
  trace_id: string;
  span_id: Array<string>;
  /** ms */
  start_time: string;
  /** ms, end_at >= start_at */
  end_time: string;
  target_env?: flow_devops_fornaxob_common.EnvType;
  transferred?: boolean;
  'x-boe-env'?: string;
}

export interface GetSpanInfoResponse {
  data: GetTraceData;
  /** Only for http requests; internal RPC is not used, unified access to Code and Msg through BaseResp */
  code?: number;
  /** Only for http requests; internal RPC is not used, unified access to Code and Msg through BaseResp */
  msg?: string;
}

export interface GetTraceByLogIDRequest {
  /** space id */
  space_id: string;
  log_id: string;
  /** ms */
  start_time: string;
  /** ms, end_at >= start_at */
  end_time: string;
  target_env?: flow_devops_fornaxob_common.EnvType;
  transferred?: boolean;
  'x-boe-env'?: string;
}

export interface GetTraceByLogIDResponse {
  data: GetTraceData;
  /** Only for http requests; internal RPC is not used, unified access to Code and Msg through BaseResp */
  code?: number;
  /** Only for http requests; internal RPC is not used, unified access to Code and Msg through BaseResp */
  msg?: string;
}

export interface GetTraceData {
  spans: Array<span.Span>;
  traces_advance_info?: TraceAdvanceInfo;
  /** Whether it is complete tree data, false: contains only tree structure information, true: contains tree structure information and span details */
  is_complete_trace?: boolean;
}

export interface GetTraceRequest {
  /** space id */
  space_id: string;
  trace_id: string;
  /** ms */
  start_time: string;
  /** ms, end_at >= start_at */
  end_time: string;
  target_env?: flow_devops_fornaxob_common.EnvType;
  transferred?: boolean;
  'x-boe-env'?: string;
  /** Platform type, if left blank, the default is fornax. */
  platform_type?: flow_devops_fornaxob_common.PlatformType;
  log_id?: string;
}

export interface GetTraceResponse {
  data: GetTraceData;
  /** Only for http requests; internal RPC is not used, unified access to Code and Msg through BaseResp */
  code?: number;
  /** Only for http requests; internal RPC is not used, unified access to Code and Msg through BaseResp */
  msg?: string;
}

export interface GetTracesMetaInfoData {
  /** field meta information */
  field_metas: Record<string, FieldMeta>;
}

export interface GetTracesMetaInfoRequest {
  /** Platform type, if left blank, the default is fornax. */
  platform_type?: flow_devops_fornaxob_common.PlatformType;
  /** The span tab type of the query, if not filled in, the default is root span. */
  span_list_type?: flow_devops_fornaxob_common.SpanListType;
  space_id?: Int64;
}

export interface GetTracesMetaInfoResponse {
  data?: GetTracesMetaInfoData;
  /** Only for http requests; internal RPC is not used, unified access to Code and Msg through BaseResp */
  code?: number;
  /** Only for http requests; internal RPC is not used, unified access to Code and Msg through BaseResp */
  msg?: string;
}

export interface IngestTracesRequest {
  /** span list */
  spans?: Array<Span>;
  Base?: base.Base;
}

export interface IngestTracesResponse {
  code?: number;
  msg?: string;
  BaseResp?: base.BaseResp;
}

export interface Item {
  status: ItemStatus;
  fields?: Record<string, string>;
  /** error message */
  errors?: Array<ItemError>;
}

export interface ItemError {
  type?: datasetv2.ItemErrorType;
  /** There is a wrong field name, not required */
  field_names?: Array<string>;
}

export interface ListAllSpansRequest {
  /** space id */
  space_id: string;
  /** ms */
  start_time: string;
  /** ms, end_at >= start_at */
  end_time: string;
  /** 4: optional list < string > AppID (agw.js_conv = "str" api.body = "app_id" go.tag = "json:\" app_id \"") // app id field is invalid */nvalid */
  filters?: Record<string, flow_devops_fornaxob_fieldfilter.FieldFilter>;
  /** Full-Text search full-text search, will search input, output, bot_version, os_version these four fields. You can pass in multiple keywords, each keyword is and relationship */
  full_text_search?: Array<string>;
  /** default 1000 */
  limit?: number;
  /** The ORDER BY is used to sort the records, in ascending or descending order.

        ORDER BY with multiple field: The system will sort the results by field1(order_by[0]), then by field2(order_by[1])

        ⚠️  WARNING: only support start_time

         Example:
        [
            {
                "field_name": "start_time",
                "order_type": "desc"
            }
        ] */
  order_by?: Array<flow_devops_fornaxob_common.OrderBy>;
  /** The page token is generated after the first query and passed in the subsequent queries
     to determine the starting point for the next page of results. */
  page_token?: string;
  target_env?: flow_devops_fornaxob_common.EnvType;
  transferred?: boolean;
  'x-boe-env'?: string;
  /** Platform type, if left blank, the default is fornax. */
  platform_type?: flow_devops_fornaxob_common.PlatformType;
  /** Whether to get only the root span */
  is_root_span_only?: boolean;
  query_and_or?: flow_devops_fornaxob_fieldfilterv2.Relation;
}

export interface ListAllSpansResponse {
  data: ListTracesData;
  /** Only for http requests; internal RPC is not used, unified access to Code and Msg through BaseResp */
  code?: number;
  /** Only for http requests; internal RPC is not used, unified access to Code and Msg through BaseResp */
  msg?: string;
}

export interface ListAnnotationEvaluatorsRequest {
  workspace_id: Int64;
  name?: string;
}

export interface ListAnnotationEvaluatorsResponse {
  evaluators: Array<AnnotationEvaluator>;
  /** Only for http requests; internal RPC is not used, unified access to Code and Msg through BaseResp */
  code?: number;
  /** Only for http requests; internal RPC is not used, unified access to Code and Msg through BaseResp */
  msg?: string;
}

export interface ListLLMSpansRequest {
  /** space id */
  space_id: string;
  /** ms */
  start_time: string;
  /** ms, end_at >= start_at */
  end_time: string;
  /** 4: optional list < string > AppID (agw.js_conv = "str" api.body = "app_id" go.tag = "json:\" app_id \"") // app id field is invalid */nvalid */
  filters?: Record<string, flow_devops_fornaxob_fieldfilter.FieldFilter>;
  /** Full-Text search full-text search, will search input, output, bot_version, os_version these four fields. You can pass in multiple keywords, each keyword is and relationship */
  full_text_search?: Array<string>;
  /** default 1000 */
  limit?: number;
  /** The ORDER BY is used to sort the records, in ascending or descending order.

        ORDER BY with multiple field: The system will sort the results by field1(order_by[0]), then by field2(order_by[1])

        ⚠️  WARNING: only support start_time

         Example:
        [
            {
                "field_name": "start_time",
                "order_type": "desc"
            }
        ] */
  order_by?: Array<flow_devops_fornaxob_common.OrderBy>;
  /** The page token is generated after the first query and passed in the subsequent queries
     to determine the starting point for the next page of results. */
  page_token?: string;
  target_env?: flow_devops_fornaxob_common.EnvType;
  transferred?: boolean;
  'x-boe-env'?: string;
  /** Platform type, if left blank, the default is fornax. */
  platform_type?: flow_devops_fornaxob_common.PlatformType;
  query_and_or?: flow_devops_fornaxob_fieldfilterv2.Relation;
}

export interface ListLLMSpansResponse {
  data: ListTracesData;
  /** Only for http requests; internal RPC is not used, unified access to Code and Msg through BaseResp */
  code?: number;
  /** Only for http requests; internal RPC is not used, unified access to Code and Msg through BaseResp */
  msg?: string;
}

export interface ListTracesData {
  spans: Array<span.Span>;
  /** The paging token on the next page, which is returned when the front end pulls the data on the next page. */
  next_page_token: string;
  /** Is there any more data? */
  has_more: boolean;
  /** Span's post-processing information */
  spans_extra?: Record<string, SpanExtra>;
}

export interface ListTracesRequest {
  /** space id */
  space_id: string;
  /** ms */
  start_time: string;
  /** ms, end_at >= start_at */
  end_time: string;
  /** 4: optional list < string > AppID (agw.js_conv = "str" api.body = "app_id" go.tag = "json:\" app_id \"") // app id field is invalid */nvalid */
  filters?: Record<string, flow_devops_fornaxob_fieldfilter.FieldFilter>;
  /** Full-Text search full-text search, will search input, output, bot_version, os_version these four fields. You can pass in multiple keywords, each keyword is and relationship */
  full_text_search?: Array<string>;
  /** default 1000 */
  limit?: number;
  /** The ORDER BY is used to sort the records, in ascending or descending order.

        ORDER BY with multiple field: The system will sort the results by field1(order_by[0]), then by field2(order_by[1])

        ⚠️  WARNING: only support start_time

         Example:
        [
            {
                "field_name": "start_time",
                "order_type": "desc"
            }
        ] */
  order_by?: Array<flow_devops_fornaxob_common.OrderBy>;
  /** The page token is generated after the first query and passed in the subsequent queries
     to determine the starting point for the next page of results. */
  page_token?: string;
  target_env?: flow_devops_fornaxob_common.EnvType;
  transferred?: boolean;
  'x-boe-env'?: string;
  /** Platform type, if left blank, the default is psm. */
  platform_type?: flow_devops_fornaxob_common.PlatformType;
  query_and_or?: flow_devops_fornaxob_fieldfilterv2.Relation;
}

export interface ListTracesResponse {
  data: ListTracesData;
  /** Only for http requests; internal RPC is not used, unified access to Code and Msg through BaseResp */
  code?: number;
  /** Only for http requests; internal RPC is not used, unified access to Code and Msg through BaseResp */
  msg?: string;
}

export interface OtelIngestTracesRequest {
  /** Pb/json bytes */
  body: Blob;
  /** Data type, optional application/x-protobuf or application/json */
  ContentType: string;
  /** Data encoding type, gzip optional */
  ContentEncoding: string;
  /** Space ID */
  SpaceID: string;
  Base?: base.Base;
}

export interface OtelIngestTracesResponse {
  /** Pb bytes of data */
  body?: Blob;
  BaseResp?: base.BaseResp;
}

export interface PreviewExportTracesToEvaluationRequest {
  workspace_id: Int64;
  span_ids: Array<string>;
  evaluation_set: EvaluationSetConfig;
  start_time?: Int64;
  end_time?: Int64;
  /** platform type */
  platform_type?: flow_devops_fornaxob_common.PlatformType;
  /** Import method, if not filled in, the default is append. */
  export_type?: ExportType;
  field_mappings?: Array<task.FieldMapping>;
}

export interface PreviewExportTracesToEvaluationResponse {
  /** preview data */
  items?: Array<Item>;
  /** summary error message */
  errors?: Array<datasetv2.ItemErrorGroup>;
  /** Only for http requests; internal RPC is not used, unified access to Code and Msg through BaseResp */
  code?: number;
  /** Only for http requests; internal RPC is not used, unified access to Code and Msg through BaseResp */
  msg?: string;
}

export interface SearchTraceV3Request {
  /** space id */
  space_id: string;
  /** Currently supports logid/traceid */
  id: string;
  search_type: SearchTraceV3Type;
  target_env?: flow_devops_fornaxob_common.EnvType;
  /** Specify the swimlane when accessing the boe data, for non-business use, and the same field of other interfaces has the same effect */
  'x-boe-env'?: string;
  transferred?: boolean;
  /** SearchTraceV3Type takes effect when it is LogID. You can choose how long to check later. If you don't pass it, check it back for one hour by default.
hour */
  scan_span_in_hour?: string;
}

export interface SearchTraceV3Response {
  data: GetTraceData;
  /** Only for http requests; internal RPC is not used, unified access to Code and Msg through BaseResp */
  code?: number;
  /** Only for http requests; internal RPC is not used, unified access to Code and Msg through BaseResp */
  msg?: string;
}

export interface Span {
  /** Span start time */
  started_at_micros: string;
  /** LogID */
  logid?: string;
  /** SpanID */
  span_id: string;
  /** Parent SpanID */
  parent_id: string;
  /** TraceID */
  trace_id: string;
  /** Span time-consuming (deprecated, using DurationMicros) */
  duration: number;
  /** PSM */
  psm?: string;
  /** CallType */
  call_type?: string;
  /** SpaceID */
  workspace_id: string;
  /** Span name */
  span_name: string;
  /** Span type */
  span_type: string;
  /** method name */
  method: string;
  /** status code */
  status_code: number;
  /** input */
  input: string;
  /** output */
  output: string;
  /** Object storage information */
  object_storage?: string;
  /** String type system tag */
  system_tags_string?: Record<string, string>;
  /** Long type system tag */
  system_tags_long?: Record<string, Int64>;
  /** Double type system tag */
  system_tags_double?: Record<string, number>;
  /** String type custom tag */
  tags_string?: Record<string, string>;
  /** Long type custom tag */
  tags_long?: Record<string, Int64>;
  /** Double type custom tag */
  tags_double?: Record<string, number>;
  /** Bool type custom tag (compatible with old structures) */
  tags_bool?: Record<string, boolean>;
  /** Byte type custom tag (compatible with old structures) */
  tags_bytes?: Record<string, string>;
  /** Span time (microseconds) */
  duration_micros?: string;
}

export interface SpanExtra {
  datasets?: Array<string>;
}

export interface TokenCost {
  /** Enter the number of tokens consumed */
  input: number;
  /** Output consumption token */
  output: number;
}

export interface TraceAdvanceInfo {
  trace_id: string;
  tokens: TokenCost;
}

/** Trace query parameters */
export interface TraceQueryParams {
  trace_id: string;
  start_time: string;
  end_time: string;
}
/* eslint-enable */
