/*
 * Copyright 2025 coze-dev Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
 
// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

import * as eval_set from './eval_set';
import * as filter from './filter';
import * as fornaxob_domain_common from './fornaxob_domain_common';

export type Int64 = string | number;

export interface AutoEvaluateConfig {
  evaluator_version_id: Int64;
  evaluator_id: Int64;
  field_mappings: Array<FieldMapping>;
}

export interface EffectiveTime {
  /** ms timestamp */
  start_at?: Int64;
  /** ms timestamp */
  end_at?: Int64;
}

export interface FieldMapping {
  /** Dataset field constraints */
  field_schema: eval_set.FieldSchema;
  trace_field_key: string;
  trace_field_jsonpath: string;
  eval_set_name?: string;
}

/** Rule */
export interface Rule {
  /** Span filter condition */
  span_filters?: filter.SpanFilters;
  /** sampling configuration */
  sampler?: Sampler;
  /** effective time window */
  effective_time?: EffectiveTime;
}

export interface Sampler {
  /** sample rate */
  sample_rate?: number;
  /** upper limit of sampling */
  sample_size?: Int64;
  /** Whether to start the task loop */
  is_cycle?: boolean;
  /** Sampling single upper limit */
  cycle_count?: Int64;
  /** Cycle interval */
  cycle_interval?: Int64;
  /** Cycle time unit */
  cycle_time_unit?: string;
}

/** Task */
export interface Task {
  /** Task ID */
  id?: Int64;
  /** name */
  name: string;
  /** describe */
  description?: string;
  /** Location */
  workspace_id?: Int64;
  /** type */
  task_type: string;
  /** state */
  task_status?: string;
  /** rule */
  rule?: Rule;
  /** configuration */
  task_config?: TaskConfig;
  /** task status details */
  task_detail?: TaskDetail;
  /** basic information */
  base_info?: fornaxob_domain_common.BaseInfo;
}

/** TaskConfig */
export interface TaskConfig {
  /** Configured evaluation rule information */
  auto_evaluate_configs?: Array<AutoEvaluateConfig>;
}

/** TaskDetail */
export interface TaskDetail {
  success_count?: Int64;
  failed_count?: Int64;
}
/* eslint-enable */
