/*
 * Copyright 2025 coze-dev Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
 
// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

import * as dp from './dp';
import * as model from './model';
import * as flow_devops_evaluation_dataset from './flow_devops_evaluation_dataset';

export type Int64 = string | number;

export interface CheckUserHasAIDPAccountReq {}

export interface CheckUserHasAIDPAccountResp {
  hasAIDPAccount?: boolean;
}

export interface CreateAnnotateTaskReq {
  spaceID: string;
  name: string;
  platform: dp.AnnotatePlatform;
  /** Enter the dataset ID */
  inputDatasetID: string;
  /** Output dataset name */
  outputDatasetName: string;
  aidpConfig?: dp.AIDPConfig;
  /** Data field mapping configuration */
  fieldMapConfig?: Array<dp.SendFieldMapping>;
}

export interface CreateAnnotateTaskResp {
  taskID?: string;
}

export interface CreateDataProcessingTaskReq {
  /** task name */
  name?: string;
  /** task type */
  taskType?: dp.TaskType;
  /** input dataset */
  inDatasetID?: string;
  /** Deprecated. Output dataset name, replaced by outDatasetNames */
  outDatasetName?: string;
  /** Output Dataset Schema */
  outDatasetSchema?: Array<dp.FieldInfo>;
  /** user script */
  userScript?: dp.UserScript;
  /** Practice running signatures */
  dryRunID?: string;
  trainingDatasetType?: model.TrainingDatasetType;
  /** Output dataset list */
  outDatasets?: Array<dp.DatasetInfo>;
  /** Type of output to dataset. Dataset, review set, result set */
  datasetType?: dp.DatasetType;
  /** Space ID */
  spaceID?: string;
}

export interface CreateDataProcessingTaskResp {
  /** Task ID */
  taskID?: string;
}

export interface CreateDatasetImportTaskReq {
  datasetID: string;
  fileType?: dp.DatasetFileType;
  dataSource?: dp.DataSource;
  overwrite?: boolean;
  /** Space ID */
  space_id?: string;
}

export interface CreateDatasetImportTaskResp {
  taskID?: string;
}

export interface DeleteDataProcessingTaskReq {
  task_id?: string;
  /** Space ID */
  spaceID?: string;
}

export interface DeleteDataProcessingTaskResp {
  taskID?: string;
}

export interface DryRunDataProcessingTaskReq {
  /** Enter the dataset ID */
  datasetID?: string;
  /** user script */
  userScript?: dp.UserScript;
  /** Number of samples, default first 10 */
  sampleCount?: number;
  trainingDatasetType?: model.TrainingDatasetType;
  /** Space ID */
  spaceID?: string;
}

export interface DryRunDataProcessingTaskResp {
  /** running result */
  results?: Array<dp.ScriptRunResultItem>;
  /** Signature, which needs to be passed to the server level when saving tasks */
  runID?: string;
  /** Schema of running results */
  schema?: Array<dp.FieldInfo>;
  /** compilation error */
  compileError?: string;
  /** standard output */
  stdout?: string;
  /** standard error */
  stderr?: string;
}

export interface ExportDatasetReq {
  spaceID: string;
  datasetID: string;
  columnMappings?: Array<dp.DatasetColumnMapping>;
  /** Provided when exporting to a new review set/result set/annotation set */
  toDatasetName?: string;
  toDatasetDesc?: string;
  toDatasetPublishOption?: flow_devops_evaluation_dataset.PublishOption;
  /** Required when creating training dataset */
  toDatasetType?: flow_devops_evaluation_dataset.DatasetType;
  toDatasetTagIDs?: Array<Int64>;
  /** Provided when exporting to an existing evaluation set/result set/annotation set */
  toDatasetID?: string;
  /** Overwrite update when true */
  overwrite?: boolean;
}

export interface ExportDatasetResp {
  taskID?: string;
}

export interface GetAnnotateTaskReq {
  taskID: string;
  spaceID: string;
}

export interface GetAnnotateTaskResp {
  taskDetail?: dp.AnnotateTask;
}

export interface GetDatasetImportTaskReq {
  task_id?: string;
  space_id?: string;
}

export interface GetDatasetImportTaskResp {
  task?: dp.DatasetImportTask;
}

export interface GetExportDatasetTaskReq {
  spaceID: string;
  taskID: string;
}

export interface GetExportDatasetTaskResp {
  task: dp.ExportDatasetTask;
}

export interface GetTaskRunLogsReq {
  run_id?: string;
  /** Space ID */
  space_id?: string;
}

export interface GetTaskRunLogsResp {
  /** log source */
  runLogSourceType?: dp.RunLogSourceType;
  /** log content */
  content?: string;
}

export interface GetTaskRunsReq {
  task_id?: string;
  /** Space ID */
  spaceID?: string;
}

export interface GetTaskRunsResp {
  runs?: Array<dp.TaskRun>;
}

export interface GetUserScriptTemplateConfigReq {
  trainingDatasetType?: model.TrainingDatasetType;
}

export interface GetUserScriptTemplateConfigResp {
  configs?: Array<dp.UserScriptTemplateConfig>;
}

export interface ListAnnotateTaskBySpaceReq {
  spaceID: string;
  /** tag platform task ID */
  platformTaskIDs?: Array<string>;
  /** Enter the dataset ID */
  inputDatasetIDs?: Array<string>;
  /** labeling platform */
  platforms?: Array<dp.AnnotatePlatform>;
  /** task status */
  statuses?: Array<dp.TaskStatus>;
  /** Fornax annotation task ID */
  taskIDs?: Array<string>;
  /** task name */
  name?: string;
  /** founder */
  createdBy?: string;
  /** Start with null, scroll to nextCursor in resp */
  cursor?: string;
  /** Default is 20. */
  pageSize?: string;
}

export interface ListAnnotateTaskBySpaceResp {
  tasks?: Array<dp.AnnotateTask>;
  nextCursor?: string;
  hasMore?: boolean;
}

export interface ListDataProcessingTasksReq {
  name?: string;
  createdBy?: string;
  taskType?: dp.TaskType;
  inDatasetIDs?: Array<string>;
  taskID?: string;
  space_id?: string;
  pageSize?: string;
  nextToken?: string;
}

export interface ListDataProcessingTasksResp {
  tasks?: Array<dp.DataProcessingTask>;
  hasMore?: boolean;
  nextToken?: string;
}

export interface MGetDataProcessingTaskReq {
  taskIDs?: Array<string>;
  /** Space ID */
  spaceID?: string;
}

export interface MGetDataProcessingTaskResp {
  tasks?: Array<dp.DataProcessingTask>;
}

export interface ProcessCallbackReq {
  runID?: Int64;
  checkpoint?: string;
  extra?: string;
  log?: string;
  'x-fornax-dp-token'?: string;
}

export interface ProcessCallbackResp {}

export interface ReentryTaskRunReq {
  task_run_id?: string;
  forceStart?: boolean;
  /** Space ID */
  spaceID?: string;
}

export interface ReentryTaskRunResp {
  taskRunID?: string;
}

export interface RefreshAnnotateTaskStatusDetailReq {
  taskID: string;
}

export interface RefreshAnnotateTaskStatusDetailResp {
  taskDetail?: dp.AnnotateTask;
}

export interface RunDataProcessingTaskReq {
  task_id?: string;
  /** Space ID */
  spaceID?: string;
}

export interface RunDataProcessingTaskResp {
  taskRunID?: string;
}

export interface StopDataProcessingTaskReq {
  task_id?: string;
  /** Space ID */
  spaceID?: string;
}

export interface StopDataProcessingTaskResp {
  taskRunID?: string;
}

export interface UpdateDataProcessingTaskReq {
  task_id?: string;
  name?: string;
  userScript?: dp.UserScript;
  dryRunID?: string;
  /** Output Dataset Schema */
  outDatasetSchema?: Array<dp.FieldInfo>;
  /** Space ID */
  spaceID?: string;
}

export interface UpdateDataProcessingTaskResp {
  /** Task ID */
  taskID?: string;
}
/* eslint-enable */
