/*
 * Copyright 2025 coze-dev Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
 
// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

import * as base from './base';
import * as user from './user';

export type Int64 = string | number;

export interface AuthComponentSDKRequest {
  /** A random string of numbers and letters */
  noncestr?: string;
  /** Timestamp (milliseconds) */
  timestamp?: Int64;
  /** Component page URL */
  url?: string;
  Base?: base.Base;
}

export interface AuthComponentSDKResponse {
  signature?: string;
  code?: number;
  msg?: string;
  BaseResp?: base.BaseResp;
}

export interface GetSessionInfoRequest {
  Base?: base.Base;
}

export interface GetSessionInfoResponse {
  /** Login user information */
  user_info?: user.UserInfoDetail;
  code?: number;
  msg?: string;
  BaseResp?: base.BaseResp;
}

export interface GetUserInfoRequest {
  /** Optional user ID */
  user_id?: string;
  /** Optional username */
  user_name?: string;
  Base?: base.Base;
}

export interface GetUserInfoResponse {
  /** user information */
  user_info?: user.UserInfoDetail;
  code?: number;
  msg?: string;
  BaseResp?: base.BaseResp;
}

export interface IsUserInGrayData {
  uid?: string;
}

export interface IsUserInGrayRequest {
  /** Grey release strategy */
  strategy?: string;
  Base?: base.Base;
}

export interface IsUserInGrayResponse {
  data?: IsUserInGrayData;
  BaseResp?: base.BaseResp;
}

export interface KickUserReq {
  extUserID: string;
  'Zti-Token': string;
  Base?: base.Base;
}

export interface KickUserResp {
  BaseResp?: base.BaseResp;
}

export interface LoginRequest {
  /** login authorization code */
  code?: string;
  /** Login process redirect uri */
  state?: string;
  /** Specify sessionID */
  session_id?: string;
  Base?: base.Base;
}

export interface LoginResponse {
  code?: number;
  msg?: string;
  BaseResp?: base.BaseResp;
}

export interface LogoutRequest {
  Base?: base.Base;
}

export interface LogoutResponse {
  code?: number;
  msg?: string;
  BaseResp?: base.BaseResp;
}

export interface MGetUserInfoRequest {
  /** Fornax UserID List */
  user_ids?: Array<string>;
  /** SsoUserName List */
  user_names?: Array<string>;
  /** Feishu UserID List */
  ext_user_ids?: Array<string>;
  Base?: base.Base;
}

export interface MGetUserInfoResponse {
  /** user information list */
  user_infos?: Array<user.UserInfoDetail>;
  code?: number;
  msg?: string;
  BaseResp?: base.BaseResp;
}

export interface QueryUserInfoRequest {
  /** Username fuzzy search */
  name_like: string;
  /** Page size, default is 20 */
  page_size?: number;
  /** Paging Token */
  page_token?: string;
  Base?: base.Base;
}

export interface QueryUserInfoResponse {
  /** user information list */
  user_infos?: Array<user.UserInfoDetail>;
  /** Paging Token */
  page_token?: string;
  /** Is there a next page? */
  has_more?: boolean;
  code?: number;
  msg?: string;
  BaseResp?: base.BaseResp;
}
/* eslint-enable */
